(function(g){var window=this;var V4=function(a,b,c){var d=b.va();g.L(a.element,"ytp-suggestion-set",!!d.videoId);var e=b.getPlaylistId();c=b.Cc(c?c:"mqdefault.jpg");var f=b instanceof g.IB&&b.lengthSeconds?g.GR(b.lengthSeconds):null,k=!!e;e=k&&"RD"==(new g.FE(e.substr(0,2),e.substr(2))).type;var l=b instanceof g.IB?b.ua:null;d={title:b.title,author:b.author,author_and_views:d.shortViewCount?b.author+" \u2022 "+d.shortViewCount:b.author,aria_label:b.mj||g.lO("$TITLE \ubcf4\uae30",{TITLE:b.title}),duration:f,url:b.bi(),is_live:l,
is_list:k,is_mix:e,background:c?"background-image: url("+c+")":""};b instanceof g.HE&&(d.playlist_length=b.getLength());a.update(d)},W4=function(a,b){g.CD.call(this,{C:"div",
X:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.player=a;this.created=!1},X4=function(a){g.W.call(this,{C:"div",
X:["ytp-upnext","ytp-player-content"],M:{"aria-label":"{{aria_label}}"},K:[{C:"div",H:"ytp-cued-thumbnail-overlay-image",M:{style:"{{background}}"}},{C:"span",H:"ytp-upnext-top",K:[{C:"span",H:"ytp-upnext-header",V:"\ub2e4\uc74c \ub3d9\uc601\uc0c1"},{C:"span",H:"ytp-upnext-title",V:"{{title}}"},{C:"span",H:"ytp-upnext-author",V:"{{author}}"}]},{C:"a",H:"ytp-upnext-autoplay-icon",M:{role:"button",href:"{{url}}","aria-label":"\ub2e4\uc74c \ub3d9\uc601\uc0c1 \uc7ac\uc0dd"},K:[{C:"svg",M:{height:"100%",
version:"1.1",viewBox:"0 0 72 72",width:"100%"},K:[{C:"circle",H:"ytp-svg-autoplay-circle",M:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{C:"circle",H:"ytp-svg-autoplay-ring",M:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{C:"path",H:"ytp-svg-fill",M:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{C:"span",H:"ytp-upnext-bottom",K:[{C:"span",H:"ytp-upnext-cancel"},
{C:"span",H:"ytp-upnext-paused",V:"\uc790\ub3d9\uc7ac\uc0dd \uc77c\uc2dc\uc911\uc9c0\ub428"}]}]});this.B=null;var b=this.i["ytp-upnext-cancel"];this.B=new g.W({C:"button",X:["ytp-upnext-cancel-button","ytp-button"],M:{tabindex:"0","aria-label":"\uc790\ub3d9\uc7ac\uc0dd \ucde8\uc18c"},V:"\ucde8\uc18c"});g.G(this,this.B);this.B.ea("click",this.XI,this);this.B.g(b);this.l=a;this.J=this.i["ytp-svg-autoplay-ring"];this.F=this.D=this.o=this.A=null;this.G=new g.M(this.fm,5E3,this);g.G(this,this.G);this.I=
0;this.L(this.i["ytp-upnext-autoplay-icon"],"click",this.JK);this.mz();this.L(a,"autonavvisibility",this.mz);this.L(a,"mdxnowautoplaying",this.cK);this.L(a,"mdxautoplaycanceled",this.dK);this.L(a,"mdxautoplayupnext",this.GB);3==this.l.getPresentingPlayerType()&&(a=(a=g.bL(g.WK(this.l)))?a.MD():null)&&this.GB(a)},Y4=function(a,b){if(!a.o){g.sq("a11y-announce","\ub2e4\uc74c \ub3d9\uc601\uc0c1 "+a.A.title);
a.I=g.Xt();a.o=new g.M((0,g.y)(a.Bp,a,b),25);a.Bp(b);var c=b||g.R(g.X(a.l).experiments,"autoplay_time")||1E4;a.l.na("onAutonavCoundownStarted",c)}g.ro(a.element,"ytp-upnext-autoplay-paused")},$4=function(a){Z4(a);
a.I=g.Xt();a.Bp();g.J(a.element,"ytp-upnext-autoplay-paused")},Z4=function(a){a.o&&(a.o.dispose(),a.o=null)},a5=function(a,b){b=void 0===b?!1:b;
if(g.P(g.X(a.l).experiments,"autonav_notifications")&&b&&window.Notification&&document.hasFocus){var c=Notification.permission;"default"==c?Notification.requestPermission():"granted"!=c||document.hasFocus()||(c=a.A.va(),a.fm(),a.D=new Notification("\ub2e4\uc74c \ub3d9\uc601\uc0c1",{body:c.title,icon:c.Cc()}),a.F=a.L(a.D,"click",a.BK),a.G.start())}Z4(a);a.l.nextVideo(!1,b)},b5=function(a){W4.call(this,a,"subscribecard-endscreen");
var b=a.getVideoData();this.l=new g.W({C:"div",H:"ytp-subscribe-card",K:[{C:"img",H:"ytp-author-image",M:{src:b.Xd}},{C:"div",H:"ytp-subscribe-card-right",K:[{C:"div",H:"ytp-author-name",V:b.author},{C:"div",H:"html5-subscribe-button-container"}]}]});g.G(this,this.l);this.l.g(this.element);this.o=new g.UW("\uad6c\ub3c5",null,"\uad6c\ub3c5 \ucde8\uc18c",null,!0,!1,b.Vf,b.subscribed,"trailer-endscreen",null,null,a);g.G(this,this.o);this.o.g(this.l.i["html5-subscribe-button-container"]);this.hide()},
c5=function(a){var b=g.X(a),c=g.Bx||g.xh?{style:"will-change: opacity"}:void 0,d=b.i,e=["ytp-videowall-still"];
b.g&&e.push("ytp-videowall-show-text");g.W.call(this,{C:"a",X:e,M:{href:"{{url}}",target:d?b.A:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},K:[{C:"div",H:"ytp-videowall-still-image",M:{style:"{{background}}"}},{C:"span",H:"ytp-videowall-still-info",K:[{C:"span",H:"ytp-videowall-still-info-bg",K:[{C:"span",H:"ytp-videowall-still-info-content",M:c,K:[{C:"span",H:"ytp-videowall-still-info-title",V:"{{title}}"},{C:"span",H:"ytp-videowall-still-info-author",
V:"{{author_and_views}}"},{C:"span",H:"ytp-videowall-still-info-live",V:"\uc2e4\uc2dc\uac04"},{C:"span",H:"ytp-videowall-still-info-duration",V:"{{duration}}"}]}]}]},{C:"span",X:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],K:[{C:"span",H:"ytp-videowall-still-listlabel-icon"},"\uc7ac\uc0dd\ubaa9\ub85d",{C:"span",H:"ytp-videowall-still-listlabel-length",K:[" (",{C:"span",V:"{{playlist_length}}"},")"]}]},{C:"span",X:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],
K:[{C:"span",H:"ytp-videowall-still-listlabel-mix-icon"},"\uad00\ub828 \uc7ac\uc0dd\ubaa9\ub85d",{C:"span",H:"ytp-videowall-still-listlabel-length",V:" (50+)"}]}]});this.B=d;this.l=a;this.o=null;this.A=new g.dt(this);g.G(this,this.A);this.ea("click",this.F);this.ea("keypress",this.G);this.A.L(a,"videodatachange",this.D);g.X(a).F&&g.$O(a.app.U,this.element,this);this.D()},d5=function(a){g.rL(a.l,a.element);
var b=a.o.va().videoId,c=a.o.getPlaylistId();g.aZ(a.l.app,b,a.o.Db,c,void 0,void 0)},e5=function(a){W4.call(this,a,"videowall-endscreen");
this.D=a;this.B=0;this.o=[];this.F=this.P=this.A=null;this.G=this.R=!1;this.N=null;this.da=new g.dt(this);g.G(this,this.da);this.I=new g.M(g.Qa(g.J,this.element,"ytp-show-tiles"),0);g.G(this,this.I);var b=new g.W({C:"button",X:["ytp-button","ytp-endscreen-previous"],M:{"aria-label":"\uc774\uc804"},K:[g.oQ()]});g.G(this,b);b.g(this.element);b.ea("click",this.nG,this);this.J=new g.xD({C:"div",H:"ytp-endscreen-content"});g.G(this,this.J);this.J.g(this.element);b=new g.W({C:"button",X:["ytp-button","ytp-endscreen-next"],
M:{"aria-label":"\ub2e4\uc74c"},K:[g.pQ()]});g.G(this,b);b.g(this.element);b.ea("click",this.mG,this);this.l=new X4(a);g.G(this,this.l);g.oL(this.player,this.l.element,4);this.hide()},f5=function(a){return g.pL(a.player)&&a.Zu()&&!a.F},g5=function(a,b){return(0,g.ge)(b.suggestions,function(c){c=g.VS(g.X(a.D),c);
g.G(a,c);return c})},h5=function(a){var b=a.Te();
b!=a.R&&(a.R=b,a.player.O("autonavvisibility"))},j5=function(a){g.EL.call(this,a);
this.g=null;this.i=new g.dt(this);g.G(this,this.i);this.l=g.X(a);i5(a)?this.g=new e5(this.player):this.l.Qa?this.g=new b5(this.player):this.g=new W4(this.player);g.G(this,this.g);g.oL(this.player,this.g.element,4);this.EA();this.i.L(a,"videodatachange",this.EA,this);this.i.L(a,g.EE("endscreen"),this.BF,this);this.i.L(a,"crx_endscreen",this.CF,this)},i5=function(a){a=g.X(a);
return a.Ia&&!a.Qa};
g.t(W4,g.CD);W4.prototype.create=function(){this.created=!0};
W4.prototype.destroy=function(){this.created=!1};
W4.prototype.Zu=function(){return!1};
W4.prototype.Te=function(){return!1};g.t(X4,g.W);g.h=X4.prototype;g.h.fm=function(){this.D&&(this.G.stop(),this.Oa(this.F),this.F=null,this.D.close(),this.D=null)};
g.h.mz=function(){g.BD(this,this.l.Te())};
g.h.BK=function(){window.focus();this.fm()};
g.h.hide=function(){g.W.prototype.hide.call(this)};
g.h.Bp=function(a){a=a||g.R(g.X(this.l).experiments,"autoplay_time")||1E4;var b=Math.min(g.Xt()-this.I,a);a=Math.min(b/a,1);this.J.setAttribute("stroke-dashoffset",-211*(a+1));1<=a&&3!=this.l.getPresentingPlayerType()?a5(this,!0):this.o&&this.o.start()};
g.h.JK=function(a){!g.$d(this.B.element,g.rs(a))&&g.YS(a,this.l)&&a5(this)};
g.h.XI=function(){g.YK(this.l,!0)};
g.h.cK=function(a){this.l.getPresentingPlayerType();this.show();Y4(this,a)};
g.h.GB=function(a){this.l.getPresentingPlayerType();this.A&&this.A.va().videoId==a.va().videoId||(this.A=a,V4(this,a,"hqdefault.jpg"))};
g.h.dK=function(){this.l.getPresentingPlayerType();Z4(this);this.hide()};
g.h.W=function(){Z4(this);this.fm();g.W.prototype.W.call(this)};g.t(b5,W4);g.t(c5,g.W);c5.prototype.F=function(a){g.YS(a,this.l,this.B,this.o.Db||void 0)&&d5(this)};
c5.prototype.G=function(a){switch(a.keyCode){case 13:case 32:g.xs(a)||(d5(this),g.ws(a))}};
c5.prototype.D=function(){var a=this.l.getVideoData(),b=g.X(this.l);this.B=a.fc?!1:b.i};g.t(e5,W4);g.h=e5.prototype;g.h.create=function(){W4.prototype.create.call(this);var a=this.player.getVideoData();a&&(this.A=g5(this,a),this.P=a);this.Nf();this.da.L(this.player,"appresize",this.Nf);this.da.L(this.player,"onVideoAreaChange",this.Nf);this.da.L(this.player,"videodatachange",this.oG);this.da.L(this.player,"autonavchange",this.Nr);this.da.L(this.player,"autonavcancel",this.lG);a=this.P.autonavState;a!=this.N&&this.Nr(a);this.da.L(this.element,"transitionend",this.ZL)};
g.h.destroy=function(){g.ft(this.da);g.nf(this.o);this.o=[];this.A=null;W4.prototype.destroy.call(this);g.ro(this.element,"ytp-show-tiles");this.I.stop();this.N=this.P.autonavState};
g.h.Zu=function(){return 1!=this.P.autonavState};
g.h.show=function(){W4.prototype.show.call(this);g.ro(this.element,"ytp-show-tiles");g.X(this.player).g?g.Bo(this.I):this.I.start();(this.G||this.F&&this.F!=this.P.clientPlaybackNonce)&&g.YK(this.player,!1);f5(this)?(h5(this),2==this.P.autonavState?g.P(g.X(this.player).experiments,"fast_autonav_in_background")&&3==this.player.getVisibilityState()?a5(this.l,!0):Y4(this.l):3==this.P.autonavState&&$4(this.l)):(g.YK(this.player,!0),h5(this))};
g.h.hide=function(){W4.prototype.hide.call(this);$4(this.l);h5(this)};
g.h.ZL=function(a){g.rs(a)==this.element&&this.Nf()};
g.h.Nf=function(){if(this.A&&this.A.length){g.J(this.element,"ytp-endscreen-paginate");var a=g.fL(this.D,!0,this.D.isFullscreen()),b=g.SD(this.D);b&&(b=b.ec()?48:32,a.width-=2*b);var c=a.width/a.height,d=96/54,e=b=2,f=Math.max(a.width/96,2),k=Math.max(a.height/54,2),l=this.A.length,m=Math.pow(2,2);var n=l*m+(Math.pow(2,2)-m);n+=Math.pow(2,2)-m;for(n-=m;0<n&&(b<f||e<k);){var p=b/2,r=e/2,w=b<=f-2&&n>=r*m,z=e<=k-2&&n>=p*m;if((p+1)/r*d/c>c/(p/(r+1)*d)&&z)n-=p*m,e+=2;else if(w)n-=r*m,b+=2;else if(z)n-=
p*m,e+=2;else break}d=!1;n>=3*m&&6>=l*m-n&&(4<=e||4<=b)&&(d=!0);m=96*b;n=54*e;c=m/n<c?a.height/n:a.width/m;c=Math.min(c,2);m*=c;n*=c;m*=g.od(a.width/m||1,1,1.21);n*=g.od(a.height/n||1,1,1.21);m=Math.floor(Math.min(a.width,m));n=Math.floor(Math.min(a.height,n));a=this.J.element;g.Mh(a,m,n);g.uh(a,{marginLeft:m/-2+"px",marginTop:n/-2+"px"});c=this.l;f=this.A[0];c.A=f;V4(c,f,"hqdefault.jpg");g.L(this.element,"ytp-endscreen-takeover",f5(this));h5(this);m+=4;n+=4;for(f=c=0;f<b;f++)for(k=0;k<e;k++)if(p=
c,r=0,d&&f>=b-2&&k>=e-2?r=1:0==k%2&&0==f%2&&(2>k&&2>f?0==k&&0==f&&(r=2):r=2),p=g.pd(p+this.B,l),0!=r){w=this.o[c];w||(w=new c5(this.player),this.o[c]=w,a.appendChild(w.element));z=Math.floor(n*k/e);var C=Math.floor(m*f/b),F=Math.floor(n*(k+r)/e)-z-4,E=Math.floor(m*(f+r)/b)-C-4;g.Ch(w.element,C,z);g.Mh(w.element,E,F);g.uh(w.element,"transitionDelay",(k+f)/20+"s");g.L(w.element,"ytp-videowall-still-mini",1==r);g.L(w.element,"ytp-videowall-still-large",2<r);r=w;p=this.A[p];r.o!=p&&(r.o=p,V4(r,p,g.po(r.element,
"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg"),p=(p=p.Db)&&p.itct)&&(w=r.l,g.X(w).F&&g.aP(w.app.U,r.element,p));c++}g.L(this.element,"ytp-endscreen-paginate",c<l);for(b=this.o.length-1;b>=c;b--)e=this.o[b],g.Wd(e.element),g.mf(e);this.o.length=c}};
g.h.oG=function(){var a=this.player.getVideoData();this.P!=a&&(this.B=0,this.A=g5(this,a),this.P=a,this.Nf())};
g.h.mG=function(){this.B+=this.o.length;this.Nf()};
g.h.nG=function(){this.B-=this.o.length;this.Nf()};
g.h.PE=function(){return!!this.l.o};
g.h.Nr=function(a){1==a?(this.G=!1,this.F=this.P.clientPlaybackNonce,Z4(this.l),this.Ga()&&this.Nf()):(this.G=!0,this.Ga()&&f5(this)&&(2==a?Y4(this.l):3==a&&$4(this.l)))};
g.h.lG=function(a){if(a){for(a=0;a<this.o.length;a++)g.sL(this.D,this.o[a].element,!0);this.Nr(1)}else this.F=null,this.G=!1;this.Nf()};
g.h.Te=function(){return this.Ga()&&f5(this)};g.t(j5,g.EL);g.h=j5.prototype;g.h.Xk=function(){var a=this.player.getVideoData(),b=!!(a&&a.suggestions&&a.suggestions.length);b=!i5(this.player)||b;a=a.Rc||g.sz(a.Pa);var c=g.AY(this.player.app);return b&&!a&&!c};
g.h.Te=function(){return this.g.Te()};
g.h.KE=function(){return this.Te()?this.g.PE():!1};
g.h.W=function(){g.kL(this.player,"endscreen");g.EL.prototype.W.call(this)};
g.h.load=function(){g.EL.prototype.load.call(this);this.g.show()};
g.h.unload=function(){g.EL.prototype.unload.call(this);this.g.hide();this.g.destroy()};
g.h.BF=function(a){this.Xk()&&(this.g.created||this.g.create(),"load"==a.getId()&&this.load())};
g.h.CF=function(a){"load"==a.getId()&&this.loaded&&this.unload()};
g.h.EA=function(){g.kL(this.player,"endscreen");var a=this.player.getVideoData();a=new g.BE(Math.max(1E3*(a.lengthSeconds-10),0),0x8000000000000,{id:"preload",namespace:"endscreen"});g.G(this,a);var b=new g.BE(0x8000000000000,0x8000000000000,{id:"load",priority:6,namespace:"endscreen"});g.G(this,b);g.hL(this.player,[a,b])};g.aW.endscreen=j5;})(_yt_player);
