(function(g){var window=this;var kqa=function(a,b){return g.Vb(a,b)},v6=function(){},lqa=function(a){if(a.Dc&&"function"==typeof a.Dc)return a.Dc();
if(g.u(a))return a.split("");if(g.La(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return g.Qb(a)},mqa=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);
else if(g.La(a)||g.u(a))(0,g.B)(a,b,void 0);else{if(a.Rd&&"function"==typeof a.Rd)var c=a.Rd();else if(a.Dc&&"function"==typeof a.Dc)c=void 0;else if(g.La(a)||g.u(a)){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=g.Rb(a);d=lqa(a);e=d.length;for(var f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}},w6=function(a){g.sn(a,"zx",Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^(0,g.H)()).toString(36));
return a},x6=function(a,b,c){g.Ka(c)||(c=[String(c)]);
g.xn(a.l,b,c)},y6=function(a){return(a=g.So(a))?new ActiveXObject(a):new XMLHttpRequest},z6=function(a,b){return b+" ["+a.aa+" "+a.F+" "+a.getStatus()+"]"},nqa=function(a){return"content-type"==a.toLowerCase()},A6=function(a){a.g&&a.J&&(a.g.ontimeout=null);
a.G&&(g.v.clearTimeout(a.G),a.G=null)},oqa=function(a){return g.Ld&&g.md(9)&&g.Fa(a.timeout)&&g.Da(a.ontimeout)},B6=function(a){a.R||(a.R=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))},C6=function(a,b){if(a.g){A6(a);
var c=a.g,d=a.T[0]?g.Ha:null;a.g=null;a.T=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){}}},D6=function(a,b){a.i=!1;
a.g&&(a.o=!0,a.g.abort(),a.o=!1);a.l=b;a.A=5;B6(a);C6(a)},E6=function(a){return a.g?a.g.readyState:0},F6=function(a){if(a.i&&"undefined"!=typeof g.qZ)if(a.T[1]&&4==E6(a)&&2==a.getStatus())z6(a,"Local request error detected and ignored");
else if(a.D&&4==E6(a))g.Cg(a.Tw,0,a);else if(a.dispatchEvent("readystatechange"),4==E6(a)){z6(a,"Request complete");a.i=!1;try{var b=a.getStatus();a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var f=g.Og(1,String(a.F));if(!f&&g.v.self&&g.v.self.location){var k=g.v.self.location.protocol;f=k.substr(0,k.length-1)}e=!pqa.test(f?f.toLowerCase():"")}d=e}if(d)a.dispatchEvent("complete"),a.dispatchEvent("success");
else{a.A=6;try{var l=2<E6(a)?a.g.statusText:""}catch(m){l=""}a.l=l+" ["+a.getStatus()+"]";B6(a)}}finally{C6(a)}}},G6=function(a){g.Mf.call(this);
this.headers=new g.gn;this.N=a||null;this.i=!1;this.T=this.g=null;this.aa=this.F="";this.A=0;this.l="";this.o=this.ba=this.D=this.R=!1;this.B=0;this.G=null;this.Y="";this.J=this.U=!1},H6=function(a){try{return a.g?a.g.responseText:""}catch(b){return""}},qqa=function(a,b){var c=[];
g.Qk(b,function(d){try{var e=g.ip.prototype.i.call(this,d,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.Da(e)?g.hp(e)&&c.push(d):c.push(d)},a);
return c},rqa=function(a,b){var c=qqa(a,b);
(0,g.B)(c,function(d){g.ip.prototype.remove.call(this,d)},a)},I6=function(a){if(a.kd){if(a.kd.locationOverrideToken)return{locationOverrideToken:a.kd.locationOverrideToken};
if(null!=a.kd.latitudeE7&&null!=a.kd.longitudeE7)return{latitudeE7:a.kd.latitudeE7,longitudeE7:a.kd.longitudeE7}}return null},sqa=function(a,b){g.$a(a,b)||a.push(b)},J6=function(a){var b=0,c;
for(c in a)b++;return b},K6=function(a,b){var c=b instanceof g.yc?b:g.Ec(b,/^data:image\//i.test(b));
a.src=g.zc(c)},tqa=function(a){try{return g.v.JSON.parse(a)}catch(b){}a=String(a);
if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);},uqa=function(a,b,c,d){var e=new g.kn(null,void 0);
a&&g.ln(e,a);b&&g.mn(e,b);c&&g.nn(e,c);d&&(e.i=d);return e},L6=function(a){if(g.v.JSON)try{return g.v.JSON.parse(a)}catch(b){}return tqa(a)},M6=function(){this.g=[];
this.i=[]},N6=function(a,b){g.nq[a]=!0;
var c=g.lq();c&&c.publish.apply(c,arguments);g.nq[a]=!1},O6=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.l=!1;this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.gn;this.g=this.i="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",vqa(this,a.capabilities||""),wqa(this,a.experiments||""),this.i=a.remoteControllerUrl||"",this.g=a.localChannelEncryptionKey||
"")},vqa=function(a,b){a.capabilities.clear();
(0,g.Xd)(b.split(","),g.Qa(kqa,xqa)).forEach(function(c){a.capabilities.add(c)})},wqa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(c){a.experiments.add(c)})},P6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},Q6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},R6=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},yqa=function(a){return new P6(a)},S6=function(a){return g.Ka(a)?(0,g.ge)(a,yqa):[]},T6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},U6=function(a){return g.Ka(a)?"["+(0,g.ge)(a,T6).join(",")+"]":"null"},V6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},zqa=function(a){return(0,g.ge)(a,function(b){return{key:b.id,
name:b.name}})},W6=function(a,b){return g.Wa(a,function(c){return c||b?!c!=!b?!1:c.id==b.id:!0})},X6=function(a,b){return g.Wa(a,function(c){return Q6(c,b)})},Y6=function(a){try{var b=(0,g.Ot)(),c=(0,g.Nt)();
b&&b.remove(a);c&&c.remove(a)}catch(d){}},Aqa=function(){var a=(0,g.Nt)();
a&&rqa(a,a.g.rf(!0))},Z6=function(){var a=g.Qt("yt-remote-connected-devices")||[];
g.qb(a);return a},Bqa=function(a){if(0==a.length)return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.ge)(a,function(d,e){return 0==e?d:d.substring(c.length)})},Cqa=function(a){g.Pt("yt-remote-connected-devices",a,86400)},a7=function(){if($6)return $6;
var a=g.Qt("yt-remote-device-id");a||(a=V6(),g.Pt("yt-remote-device-id",a,31536E3));for(var b=Z6(),c=1,d=a;g.$a(b,d);)c++,d=a+"#"+c;return $6=d},b7=function(){var a=Z6(),b=a7();
g.$a(a,b);g.Rt()&&g.sb(a,b);a=Bqa(a);if(0==a.length)try{g.Ms("remote_sid")}catch(c){}else try{g.Ls("remote_sid",a.join(","),-1)}catch(c){}},Dqa=function(){return g.Qt("yt-remote-session-browser-channel")},Eqa=function(){return g.Qt("yt-remote-local-screens")||[]},Fqa=function(){g.Pt("yt-remote-lounge-token-expiration",!0,86400)},Gqa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.ge)(Eqa(),function(d){return d.loungeToken}),c=(0,g.ge)(a,function(d){return d.loungeToken});
(0,g.jj)(c,function(d){return!g.$a(b,d)})&&Fqa();
g.Pt("yt-remote-local-screens",a,31536E3)},Hqa=function(a,b){g.Pt("yt-remote-session-browser-channel",a);
g.Pt("yt-remote-session-screen-id",b);var c=Z6(),d=a7();g.$a(c,d)||c.push(d);Cqa(c);b7()},c7=function(a){a||(Y6("yt-remote-session-screen-id"),Y6("yt-remote-session-video-id"));
b7();a=Z6();g.cb(a,a7());Cqa(a)},Iqa=function(){if(!d7){var a=g.sp();
a&&(d7=new g.cp(a))}return d7?!!d7.get("yt-remote-use-staging-server"):!1},Jqa=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},Kqa=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},e7=function(a){a.length?Lqa(a.shift(),function(){e7(a)}):f7()},Mqa=function(a){return"chrome-extension://"+a+"/cast_sender.js"},Lqa=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(document.head||document.documentElement).appendChild(d)},f7=function(){var a=Kqa();
a&&a(!1,"No cast extension found")},Oqa=function(){if(Nqa){var a=2,b=Kqa(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;Lqa("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",f7,c)}},Pqa=function(){Oqa();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);e7(["//www.gstatic.com/eureka/clank/"+(a?parseInt(a[1],10):0)+"/cast_sender.js","//www.gstatic.com/eureka/clank/cast_sender.js"])},g7=function(a,b,c){g.D.call(this);
this.B=null!=c?(0,g.y)(a,c):a;this.cd=b;this.A=(0,g.y)(this.RD,this);this.g=!1;this.i=0;this.l=this.Ba=null;this.o=[]},h7=function(){},i7=function(a,b,c,d){this.g=a;
this.l=b;this.D=c;this.B=d||1;this.o=45E3;this.da=new g.yn(this);this.i=new g.Bg;this.i.setInterval(250)},Rqa=function(a,b,c){a.di=1;
a.cg=w6(b.clone());a.wh=c;a.A=!0;Qqa(a,null)},j7=function(a,b,c,d,e){a.di=1;
a.cg=w6(b.clone());a.wh=null;a.A=c;e&&(a.KA=!1);Qqa(a,d)},Qqa=function(a,b){a.Ki=(0,g.H)();
k7(a);a.Gg=a.cg.clone();x6(a.Gg,"t",a.B);a.sl=0;a.wc=a.g.eq(a.g.al()?b:null);0<a.Lq&&(a.mo=new g.Il((0,g.y)(a.QB,a,a.wc),a.Lq));a.da.ea(a.wc,"readystatechange",a.OM);var c=a.eh?g.cc(a.eh):{};a.wh?(a.Ro="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.wc.send(a.Gg,a.Ro,a.wh,c)):(a.Ro="GET",a.KA&&!g.Nd&&(c.Connection="close"),a.wc.send(a.Gg,a.Ro,null,c));a.g.Ce(1)},Uqa=function(a,b,c){for(var d=!0;!a.Rg&&a.sl<c.length;){var e=Sqa(a,c);
if(e==l7){4==b&&(a.sg=4,m7(15),d=!1);break}else if(e==Tqa){a.sg=4;m7(16);d=!1;break}else n7(a,e)}4==b&&0==c.length&&(a.sg=1,m7(17),d=!1);a.Fe=a.Fe&&d;d||(o7(a),p7(a))},Sqa=function(a,b){var c=a.sl,d=b.indexOf("\n",c);
if(-1==d)return l7;c=Number(b.substring(c,d));if(isNaN(c))return Tqa;d+=1;if(d+c>b.length)return l7;var e=b.substr(d,c);a.sl=d+c;return e},Wqa=function(a,b){a.Ki=(0,g.H)();
k7(a);var c=b?window.location.hostname:"";a.Gg=a.cg.clone();g.sn(a.Gg,"DOMAIN",c);g.sn(a.Gg,"t",a.B);try{a.Je=new ActiveXObject("htmlfile")}catch(n){o7(a);a.sg=7;m7(22);p7(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in q7)k=q7[l];else if(l in Vqa)k=q7[l]=Vqa[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=m.toString(16).toUpperCase()}k=
q7[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.Sc(g.rc("b/12014412"),d+"</body></html>");a.Je.open();a.Je.write(g.Nc(c));a.Je.close();a.Je.parentWindow.m=(0,g.y)(a.cM,a);a.Je.parentWindow.d=(0,g.y)(a.Tz,a,!0);a.Je.parentWindow.rpcClose=(0,g.y)(a.Tz,a,!1);c=a.Je.createElement("DIV");a.Je.parentWindow.document.body.appendChild(c);d=g.Dc(a.Gg.toString());d=g.Zc(g.Ac(d));d=g.Sc(g.rc("b/12014412"),'<iframe src="'+d+'"></iframe>');g.Tc(c,d);a.g.Ce(1)},k7=function(a){a.Tt=(0,g.H)()+a.o;
Xqa(a,a.o)},Xqa=function(a,b){if(null!=a.aj)throw Error("WatchDog timer not null");
a.aj=r7((0,g.y)(a.mM,a),b)},s7=function(a){a.aj&&(g.v.clearTimeout(a.aj),a.aj=null)},p7=function(a){a.g.Rw()||a.Rg||a.g.Xn(a)},o7=function(a){s7(a);
g.mf(a.mo);a.mo=null;a.i.stop();g.An(a.da);if(a.wc){var b=a.wc;a.wc=null;b.abort();b.dispose()}a.Je&&(a.Je=null)},n7=function(a,b){try{a.g.Nz(a,b),a.g.Ce(4)}catch(c){}},Zqa=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;Yqa(a,b,function(k){k?c(!0):g.v.setTimeout(function(){Zqa(a,b,c,d,f)},f)})}},Yqa=function(a,b,c){var d=new Image;
d.onload=function(){try{t7(d),c(!0)}catch(e){}};
d.onerror=function(){try{t7(d),c(!1)}catch(e){}};
d.onabort=function(){try{t7(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{t7(d),c(!1)}catch(e){}};
g.v.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
K6(d,a)},t7=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},$qa=function(a){this.g=a;
this.i=new h7},ara=function(a){var b=u7(a.g,a.pj,"/mail/images/cleardot.gif");
w6(b);Zqa(b.toString(),5E3,(0,g.y)(a.ZC,a),3,2E3);a.Ce(1)},w7=function(a){var b=a.g.G;
if(null!=b)m7(5),b?(m7(11),v7(a.g,a,!1)):(m7(12),v7(a.g,a,!0));else if(a.Id=new i7(a,void 0,void 0,void 0),a.Id.eh=a.Jq,b=a.g,b=u7(b,b.al()?a.Vj:null,a.Kq),m7(5),!g.Ld||g.nd(10))x6(b,"TYPE","xmlhttp"),j7(a.Id,b,!1,a.Vj,!1);else{x6(b,"TYPE","html");var c=a.Id;a=!!a.Vj;c.di=3;c.cg=w6(b.clone());Wqa(c,a)}},x7=function(a,b,c){this.g=1;
this.i=[];this.o=[];this.A=new h7;this.F=a||null;this.G=null!=b?b:null;this.B=c||!1},bra=function(a,b){this.g=a;
this.map=b;this.context=null},cra=function(a){g.of.call(this,"statevent",a)},dra=function(a,b){g.of.call(this,"timingevent",a);
this.size=b},era=function(a){g.of.call(this,"serverreachability",a)},hra=function(a){fra(a);
if(3==a.g){var b=a.Ek++,c=a.sm.clone();g.sn(c,"SID",a.l);g.sn(c,"RID",b);g.sn(c,"TYPE","terminate");y7(a,c);b=new i7(a,a.l,b,void 0);b.di=2;b.cg=w6(c.clone());K6(new Image,b.cg.toString());b.Ki=(0,g.H)();k7(b)}gra(a)},ira=function(a){a.rD(1,0);
a.sm=u7(a,null,a.Iq);z7(a)},fra=function(a){a.jg&&(a.jg.abort(),a.jg=null);
a.Ub&&(a.Ub.cancel(),a.Ub=null);a.sf&&(g.v.clearTimeout(a.sf),a.sf=null);A7(a);a.Fd&&(a.Fd.cancel(),a.Fd=null);a.qg&&(g.v.clearTimeout(a.qg),a.qg=null)},jra=function(a,b){if(0==a.g)throw Error("Invalid operation: sending map when state is closed");
a.i.push(new bra(a.qI++,b));2!=a.g&&3!=a.g||z7(a)},z7=function(a){a.Fd||a.qg||(a.qg=r7((0,g.y)(a.Sz,a),0),a.Wh=0)},lra=function(a,b){if(1==a.g){if(!b){a.Ek=Math.floor(1E5*Math.random());
var c=a.Ek++,d=new i7(a,"",c,void 0);d.eh=null;var e=B7(a),f=a.sm.clone();g.sn(f,"RID",c);g.sn(f,"CVER","1");y7(a,f);Rqa(d,f,e);a.Fd=d;a.g=2}}else 3==a.g&&(b?kra(a,b):0==a.i.length||a.Fd||kra(a))},kra=function(a,b){if(b)if(6<a.Sg){a.i=a.o.concat(a.i);
a.o.length=0;var c=a.Ek-1;var d=B7(a)}else c=b.D,d=b.wh;else c=a.Ek++,d=B7(a);var e=a.sm.clone();g.sn(e,"SID",a.l);g.sn(e,"RID",c);g.sn(e,"AID",a.pi);y7(a,e);c=new i7(a,a.l,c,a.Wh+1);c.eh=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.Fd=c;Rqa(c,e,d)},y7=function(a,b){if(a.Yc){var c=a.Yc.rw();
c&&g.Kb(c,function(d,e){g.sn(b,e,d)})}},B7=function(a){var b=Math.min(a.i.length,1E3),c=["count="+b];
if(6<a.Sg&&0<b){var d=a.i[0].g;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.i[e].g,k=a.i[e].map;f=6>=a.Sg?e:f-d;try{g.Kb(k,function(l,m){c.push("req"+f+"_"+m+"="+encodeURIComponent(l))})}catch(l){c.push("req"+f+"_type="+encodeURIComponent("_badmap"))}}a.o=a.o.concat(a.i.splice(0,b));
return c.join("&")},mra=function(a){a.Ub||a.sf||(a.D=1,a.sf=r7((0,g.y)(a.Rz,a),0),a.Ph=0)},C7=function(a){if(a.Ub||a.sf||3<=a.Ph)return!1;
a.D++;a.sf=r7((0,g.y)(a.Rz,a),nra(a,a.Ph));a.Ph++;return!0},v7=function(a,b,c){a.Po=c;
a.Oe=b.Df;a.B||ira(a)},A7=function(a){null!=a.Wg&&(g.v.clearTimeout(a.Wg),a.Wg=null)},nra=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},D7=function(a,b){if(2==b||9==b){var c=null;
a.Yc&&(c=null);var d=(0,g.y)(a.tN,a);c||(c=new g.kn("//www.google.com/images/cleardot.gif"),w6(c));Yqa(c.toString(),1E4,d)}else m7(2);ora(a,b)},ora=function(a,b){a.g=0;
a.Yc&&a.Yc.qv(b);gra(a);fra(a)},gra=function(a){a.g=0;
a.Oe=-1;if(a.Yc)if(0==a.o.length&&0==a.i.length)a.Yc.Op();else{g.fb(a.o);var b=g.fb(a.i);a.o.length=0;a.i.length=0;a.Yc.Op(b)}},u7=function(a,b,c){var d=g.tn(c);
if(""!=d.g)b&&g.mn(d,b+"."+d.g),g.nn(d,d.A);else{var e=window.location;d=uqa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.Dj&&g.Kb(a.Dj,function(f,k){g.sn(d,k,f)});
g.sn(d,"VER",a.Sg);y7(a,d);return d},r7=function(a,b){if(!g.Ma(a))throw Error("Fn must not be null and must be a function");
return g.v.setTimeout(function(){a()},b)},m7=function(a){E7.dispatchEvent(new cra(E7,a))},pra=function(){},qra=function(a,b){this.action=a;
this.params=b||{}},F7=function(a,b){g.D.call(this);
this.g=new g.M(this.UL,0,this);g.G(this,this.g);this.cd=5E3;this.i=0;if(g.Ma(a))b&&(a=(0,g.y)(a,b));else if(a&&g.Ma(a.handleEvent))a=(0,g.y)(a.handleEvent,a);else throw Error("Invalid listener argument");this.l=a},G7=function(a,b,c){this.I=a;
this.B=b;this.l=new g.bp;this.i=new F7(this.YM,this);this.g=null;this.kb=!1;this.A=null;this.G="";this.F=this.o=0;this.D=[];this.J=c||!1},rra=function(a){return{firstTestResults:[""],
secondTestResults:!a.g.Po,sessionId:a.g.l,arrayId:a.g.pi}},sra=function(a,b){a.F=b||0;
a.i.stop();a.g&&(3==a.g.g&&lra(a.g),hra(a.g));a.F=0},H7=function(a){return!!a.g&&3==a.g.g},tra=function(a,b){(a.B.loungeIdToken=b)||a.i.stop()},I7=function(a){this.port=this.domain="";
this.g="/api/lounge";this.i=!0;a=a||document.location.href;var b=Number(g.Og(4,a))||"";b&&(this.port=":"+b);this.domain=g.Pg(a)||"";a=g.Ib;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Hb(a,"10.0")&&(this.i=!1))},J7=function(a,b){var c=a.g;
if(g.Da(void 0)?0:a.i)c="https://"+a.domain+a.port+a.g;return g.Yg(c+b,{})},K7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Qa(a.o,d,!0),onError:g.Qa(a.l,e),re:g.Qa(a.A,e)};c&&(a.wb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.fr(b,a)},xra=function(){var a=ura;
vra();L7.push(a);wra(L7)},M7=function(a,b){vra();
var c=L7,d=yra(a,String(b));0==c.length?zra(d):(wra(c),(0,g.B)(c,function(e){e(d)}))},vra=function(){L7||(L7=g.x("yt.mdx.remote.debug.handlers_")||[],g.Ga("yt.mdx.remote.debug.handlers_",L7,void 0))},zra=function(a){var b=(N7+1)%50;
N7=b;O7[b]=a;P7||(P7=49==b)},wra=function(a){var b=O7;
if(b[0]){var c=N7,d=P7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.B)(a,function(f){f(e)})}while(d!=c);
O7=Array(50);N7=-1;P7=!1}},yra=function(a,b){var c=((0,g.H)()-Ara)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},Q7=function(a){g.O.call(this);
this.D=a;this.g=[]},Bra=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.g.push(b);return!0},Cra=function(a,b){var c=a.g.length!=b.length;
a.g=(0,g.Xd)(a.g,function(f){return!!W6(b,f)});
for(var d=0,e=b.length;d<e;d++)c=Bra(a,b[d])||c;return c},Dra=function(a,b){var c=a.g.length;
a.g=(0,g.Xd)(a.g,function(d){return!(d||b?!d!=!b?0:d.id==b.id:1)});
return a.g.length<c},R7=function(a,b,c,d){g.O.call(this);
this.B=a;this.A=b;this.l=c;this.o=d;this.i=0;this.g=null;this.Ba=NaN},T7=function(a){Q7.call(this,"LocalScreenService");
this.l=a;this.i=NaN;S7(this);this.info("Initializing with "+U6(this.g))},Era=function(a){if(a.g.length){var b=(0,g.ge)(a.g,function(d){return d.id}),c=J7(a.l,"/pairing/get_lounge_token_batch");
K7(a.l,c,{screen_ids:b.join(",")},(0,g.y)(a.bE,a),(0,g.y)(a.aE,a))}},S7=function(a){var b=S6(Eqa());
b=(0,g.Xd)(b,function(c){return!c.uuid});
return Cra(a,b)},U7=function(a,b){Gqa((0,g.ge)(a.g,R6));
b&&Fqa()},W7=function(a,b){g.O.call(this);
this.B=b;var c=g.Qt("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.B(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.$a(c,l)}this.g=d;this.A=a;this.l=this.o=NaN;this.i=null;V7("Initialized with "+g.Gg(this.g))},Fra=function(a,b,c){var d=J7(a.A,"/pairing/get_screen_availability");
K7(a.A,d,{lounge_token:b.token},(0,g.y)(function(e){e=e.screens||[];for(var f=0,k=e.length;f<k;++f)if(e[f].loungeToken==b.token){c("online"==e[f].status);return}c(!1)},a),(0,g.y)(function(){c(!1)},a))},X7=function(a,b){a:if(J6(b)!=J6(a.g))var c=!1;
else{c=g.Rb(b);for(var d=0,e=c.length;d<e;++d)if(!a.g[c[d]]){c=!1;break a}c=!0}c||(V7("Updated online screens: "+g.Gg(a.g)),a.g=b,a.O("screenChange"));Gra(a)},Y7=function(a){isNaN(a.l)||g.kq(a.l);
a.l=g.iq((0,g.y)(a.Vs,a),0<a.o&&a.o<(0,g.H)()?2E4:1E4)},V7=function(a){M7("OnlineScreenService",a)},Hra=function(a){var b={};
(0,g.B)(a.B(),function(c){c.token?b[c.token]=c.id:this.Kb("Requesting availability of screen w/o lounge token.")});
return b},Gra=function(a){a=g.Rb(g.Lb(a.g,function(b){return b}));
g.qb(a);a.length?g.Pt("yt-remote-online-screen-ids",a.join(","),60):Y6("yt-remote-online-screen-ids")},Z7=function(a){Q7.call(this,"ScreenService");
this.B=a;this.i=this.l=null;this.o=[];this.A={};Ira(this)},Kra=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.A[b]);var k=a.Td();if(k=(c?X6(k,c):null)||X6(k,b)){k.uuid=b;var l=$7(a,k);Fra(a.i,l,function(m){e(m?l:null)})}else c?Jra(a,c,(0,g.y)(function(m){var n=$7(this,new P6({name:d,
screenId:c,loungeToken:m,dialId:b||""}));Fra(this.i,n,function(p){e(p?n:null)})},a),f):e(null)},Lra=function(a,b){for(var c=0,d=a.g.length;c<d;++c)if(a.g[c].name==b)return a.g[c];
return null},Jra=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={wb:{screen_ids:b},method:"POST",context:a,onSuccess:function(f,k){var l=k&&k.screens||[];l[0]&&l[0].screenId==b?c(l[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.fr(J7(a.B,"/pairing/get_lounge_token_batch"),e)},Mra=function(a){a.g=a.l.Td();
var b=a.A,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.g.length;b<d;++b){var e=a.g[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+U6(a.g))},Ira=function(a){a8(a);
a.l=new T7(a.B);a.l.subscribe("screenChange",(0,g.y)(a.jE,a));Mra(a);a.o=S6(g.Qt("yt-remote-automatic-screen-cache")||[]);a8(a);a.info("Initializing automatic screens: "+U6(a.o));a.i=new W7(a.B,(0,g.y)(a.Td,a,!0));a.i.subscribe("screenChange",(0,g.y)(function(){this.O("onlineScreenChange")},a))},$7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=X6(a.o,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.o.push(b),g.Pt("yt-remote-automatic-screen-cache",(0,g.ge)(a.o,R6)));a8(a);a.A[b.uuid]=b.id;g.Pt("yt-remote-device-id-map",a.A,31536E3);return b},a8=function(a){a.A=g.Qt("yt-remote-device-id-map")||{}},b8=function(a,b,c){g.O.call(this);
this.T=c;this.G=a;this.i=b;this.l=null},c8=function(a,b){M7(a.T,b)},d8=function(a,b){b8.call(this,a,b,"CastSession");
this.g=null;this.o=0;this.B=(0,g.y)(this.ZN,this);this.A=(0,g.y)(this.xM,this);this.o=g.iq((0,g.y)(function(){Nra(this,null)},this),12E4)},Ora=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.Gg(void 0));
var b={type:"getMdxSessionStatus"};a.g?a.g.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.Ha,(0,g.y)(function(){c8(this,"Failed to send message: getMdxSessionStatus.")},a)):c8(a,"Sending yt message without session: "+g.Gg(b))},Nra=function(a,b){g.kq(a.o);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.l||a.l.id!=b){var c=(0,g.y)(a.Zn,a),d=(0,g.y)(a.Wd,a);a.Jw(b,c,d,5)}}else a.Wd(Error("Waiting for session status timed out."))},e8=function(a,b,c){b8.call(this,a,b,"DialSession");
this.o=this.F=null;this.I="";this.N=c;this.A=null;this.D=g.Ha;this.B=NaN;this.J=(0,g.y)(this.cO,this);this.g=g.Ha},Pra=function(a){a.g=a.G.VB(a.I,a.i.label,a.i.friendlyName,(0,g.y)(function(b){this.g=g.Ha;
this.Zn(b)},a),(0,g.y)(function(b){this.g=g.Ha;
this.Wd(b)},a))},Qra=function(a){var b={};
b.pairingCode=a.I;b.theme=a.N;if(a.A){var c=a.A.currentTime||0;b.v=a.A.videoId;b.t=c}Iqa()&&(b.env_useStageMdx=1);return g.Wg(b)},f8=function(a,b){b8.call(this,a,b,"ManualSession");
this.g=g.iq((0,g.y)(this.si,this,null),150)},g8=function(a,b,c,d){g.O.call(this);
this.i=a;this.D=b||"233637DE";this.B=c||"cl";this.F=d||!1;this.g=null;this.A=!1;this.l=[];this.o=(0,g.y)(this.cL,this)},Rra=function(a,b){return b?g.Wa(a.l,function(c){return Q6(b,c.label)},a):null},h8=function(a){M7("Controller",a)},ura=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},i8=function(a){return a.A||!!a.l.length||!!a.g},j8=function(a,b,c){b!=a.g&&(g.mf(a.g),(a.g=b)?(c?a.O("yt-remote-cast2-receiver-resumed",b.i):a.O("yt-remote-cast2-receiver-selected",
b.i),b.subscribe("sessionScreen",(0,g.y)(a.Qz,a,b)),b.l?a.O("yt-remote-cast2-session-change",b.l):c&&a.g.si(null)):a.O("yt-remote-cast2-session-change",null))},Sra=function(a){var b=a.i.UB(),c=a.g&&a.g.i;
a=(0,g.ge)(b,function(d){c&&Q6(d,c.label)&&(c=null);var e=d.uuid?d.uuid:d.id,f=Rra(this,d);f?(f.label=e,f.friendlyName=d.name):(f=new chrome.cast.Receiver(e,d.name),f.receiverType=chrome.cast.ReceiverType.CUSTOM);return f},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},Yra=function(a,b,c,d,e,f,k){Tra()?Ura(b,e,f,k)&&(l8(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?Vra(a,c):(window.__onGCastApiAvailable=function(l,m){l?Vra(a,c):(m8("Failed to load cast API: "+m),n8(!1),l8(!1),Y6("yt-remote-cast-available"),Y6("yt-remote-cast-receiver"),Wra(),c(!1))},d?g.vq("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):
0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?Pqa():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?f7():(Oqa(),e7(Xra.map(Mqa))))):k8("Cannot initialize because not running Chrome")},Wra=function(){k8("dispose");
var a=o8();a&&a.dispose();g.Ga("yt.mdx.remote.cloudview.instance_",null,void 0);Zra(!1);g.qq(p8);p8.length=0},q8=function(){return!!g.Qt("yt-remote-cast-installed")},$ra=function(){var a=g.Qt("yt-remote-cast-receiver");
return a?a.friendlyName:null},asa=function(){k8("clearCurrentReceiver");
Y6("yt-remote-cast-receiver")},bsa=function(){return q8()?o8()?o8().getCastSession():(m8("getCastSelector: Cast is not initialized."),null):(m8("getCastSelector: Cast API is not installed!"),null)},s8=function(){q8()?o8()?r8()?(k8("Requesting cast selector."),o8().requestSession()):(k8("Wait for cast API to be ready to request the session."),p8.push(g.pq("yt-remote-cast2-api-ready",s8))):m8("requestCastSelector: Cast is not initialized."):m8("requestCastSelector: Cast API is not installed!")},t8=
function(a,b){r8()?o8().setConnectedScreenStatus(a,b):m8("setConnectedScreenStatus called before ready.")},Tra=function(){var a=0<=g.Ib.search(/ (CrMo|Chrome|CriOS)\//);
return g.Bx||a},csa=function(a,b){o8().init(a,b)},Ura=function(a,b,c,d){var e=!1;
o8()||(a=new g8(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(f){g.Pt("yt-remote-cast-available",f);N6("yt-remote-cast2-availability-change",f)}),a.subscribe("yt-remote-cast2-receiver-selected",function(f){k8("onReceiverSelected: "+f.friendlyName);
g.Pt("yt-remote-cast-receiver",f);N6("yt-remote-cast2-receiver-selected",f)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(f){k8("onReceiverResumed: "+f.friendlyName);
g.Pt("yt-remote-cast-receiver",f)}),a.subscribe("yt-remote-cast2-session-change",function(f){k8("onSessionChange: "+T6(f));
f||Y6("yt-remote-cast-receiver");N6("yt-remote-cast2-session-change",f)}),g.Ga("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
k8("cloudview.createSingleton_: "+e);return e},o8=function(){return g.x("yt.mdx.remote.cloudview.instance_")},Vra=function(a,b){n8(!0);
l8(!1);csa(a,function(c){c?(Zra(!0),g.sq("yt-remote-cast2-api-ready")):(m8("Failed to initialize cast API."),n8(!1),Y6("yt-remote-cast-available"),Y6("yt-remote-cast-receiver"),Wra());b(c)})},k8=function(a){M7("cloudview",a)},m8=function(a){M7("cloudview",a)},n8=function(a){k8("setCastInstalled_ "+a);
g.Pt("yt-remote-cast-installed",a)},r8=function(){return!!g.x("yt.mdx.remote.cloudview.apiReady_")},Zra=function(a){k8("setApiReady_ "+a);
g.Ga("yt.mdx.remote.cloudview.apiReady_",a,void 0)},l8=function(a){g.Ga("yt.mdx.remote.cloudview.initializing_",a,void 0)},u8=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.B=this.D=0;this.g=null;this.hasNext=this.Pe=!1;this.G=this.F=this.i=this.o=0;this.l=NaN;this.A=!1;this.reset(a)},v8=function(a){a.audioTrackId=null;
a.g=null;a.playerState=-1;a.Pe=!1;a.hasNext=!1;a.D=0;a.B=(0,g.H)();a.o=0;a.i=0;a.F=0;a.G=0;a.l=NaN;a.A=!1},w8=function(a){return 1==a.playerState?((0,g.H)()-a.B)/1E3:0},x8=function(a,b){a.D=b;
a.B=(0,g.H)()},y8=function(a){switch(a.playerState){case 1:case 1081:return((0,g.H)()-a.B)/1E3+a.D;
case -1E3:return 0}return a.D},z8=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&v8(a)},A8=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.dc(a.g);b.hasPrevious=a.Pe;b.hasNext=a.hasNext;b.playerTime=a.D;b.playerTimeAt=a.B;b.seekableStart=a.o;b.seekableEnd=a.i;b.duration=a.F;b.loadedTime=a.G;b.liveIngestionTime=a.l;return b},C8=function(a,b){g.O.call(this);
this.g=0;this.o=a;this.B=[];this.A=new M6;this.l=this.i=null;this.G=(0,g.y)(this.aJ,this);this.D=(0,g.y)(this.Hk,this);this.F=(0,g.y)(this.ZI,this);this.I=(0,g.y)(this.nJ,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.Wt,this),dsa(this))):c=3;0!=c&&(b?this.Wt(c):g.iq((0,g.y)(function(){this.Wt(c)},this),0));
var d=bsa();d&&B8(this,d);this.subscribe("yt-remote-cast2-session-change",this.I)},D8=function(a){return new u8(a.o.getPlayerContextData())},dsa=function(a){(0,g.B)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(b){this.B.push(this.o.subscribe(b,g.Qa(this.ZK,b),this))},a)},esa=function(a){(0,g.B)(a.B,function(b){this.o.unsubscribeByKey(b)},a);
a.B.length=0},E8=function(a,b){var c=a.A;
50>c.g.length+c.i.length&&a.A.i.push(b)},G8=function(a,b,c){var d=D8(a);
x8(d,c);-1E3!=d.playerState&&(d.playerState=b);F8(a,d)},H8=function(a,b,c){a.o.sendMessage(b,c)},F8=function(a,b){esa(a);
a.o.setPlayerContextData(A8(b));dsa(a)},B8=function(a,b){a.l&&(a.l.removeUpdateListener(a.G),a.l.removeMediaListener(a.D),a.Hk(null));
a.l=b;a.l&&(M7("CP","Setting cast session: "+a.l.sessionId),a.l.addUpdateListener(a.G),a.l.addMediaListener(a.D),a.l.media.length&&a.Hk(a.l.media[0]))},fsa=function(a){var b=a.i.media,c=a.i.customData;
if(b&&c){var d=D8(a);b.contentId!=d.videoId&&M7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;x8(d,a.i.getEstimatedTime());F8(a,d)}else M7("CP","No cast media video. Ignoring state update.")},I8=function(a,b,c){return(0,g.y)(function(d){this.Kb("Failed to "+b+" with cast v2 channel. Error code: "+d.code);
d.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.Kb("Retrying "+b+" using MDx browser channel."),H8(this,b,c))},a)},J8=function(a,b,c){g.O.call(this);
this.A=NaN;this.J=!1;this.F=this.D=this.G=this.I=NaN;this.T=[];this.o=this.B=this.l=this.Ra=this.g=null;this.R=a;this.T.push(g.ps(window,"beforeunload",(0,g.y)(this.UD,this)));this.i=[];this.Ra=new u8;this.N=b.id;this.g=gsa(this,c);this.g.subscribe("handlerOpened",this.eJ,this);this.g.subscribe("handlerClosed",this.bJ,this);this.g.subscribe("handlerError",this.cJ,this);this.g.subscribe("handlerMessage",this.dJ,this);tra(this.g,b.token);this.subscribe("remoteQueueChange",function(){var d=this.Ra.videoId;
g.Rt()&&g.Pt("yt-remote-session-video-id",d)},this)},K8=function(a){M7("conn",a)},gsa=function(a,b){return new G7(J7(a.R,"/bc"),b)},L8=function(a,b){a.O("proxyStateChange",b)},hsa=function(a){a.A=g.iq((0,g.y)(function(){K8("Connecting timeout");
this.Th(1)},a),2E4)},M8=function(a){g.kq(a.A);
a.A=NaN},N8=function(a){g.kq(a.I);
a.I=NaN},isa=function(a){O8(a);
a.G=g.iq((0,g.y)(function(){P8(this,"getNowPlaying")},a),2E4)},O8=function(a){g.kq(a.G);
a.G=NaN},ksa=function(a,b){b&&(M8(a),N8(a));
b==(H7(a.g)&&isNaN(a.A))?b&&(L8(a,1),P8(a,"getSubtitlesTrack")):b?(a.Hw()&&a.Ra.reset(),L8(a,1),P8(a,"getNowPlaying"),jsa(a)):a.Th(1)},lsa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.Ra.videoId&&(g.Yb(b.params)?a.Ra.g=null:a.Ra.g=b.params,a.O("remotePlayerChange"))},msa=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.Ra.listId=b.params.listId||a.Ra.listId;z8(a.Ra,c,d);a.O("remoteQueueChange")},osa=function(a,b){b.params=b.params||{};
msa(a,b);nsa(a,b);a.O("autoplayDismissed")},nsa=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
x8(a.Ra,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.Ra.playerState&&(c=-1E3);a.Ra.playerState=c;c=Number(b.params.loadedTime);a.Ra.G=isNaN(c)?0:c;c=Number(b.params.duration);a.Ra.F=isNaN(c)?0:c;c=a.Ra;var d=Number(b.params.liveIngestionTime);c.l=d;c.A=isNaN(d)?!1:!0;c=a.Ra;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.o=isNaN(d)?0:d;c.i=isNaN(e)?0:e;1==a.Ra.playerState?isa(a):O8(a);a.O("remotePlayerChange")},psa=function(a,b){if(-1E3!=
a.Ra.playerState){var c=1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.Ra.playerState=c;c=parseInt(b.params.currentTime,10);x8(a.Ra,isNaN(c)?0:c);a.O("remotePlayerChange")}},qsa=function(a,b){var c="true"==b.params.muted;
a.Ra.volume=parseInt(b.params.volume,10);a.Ra.muted=c;a.O("remotePlayerChange")},rsa=function(a,b){a.B=b.params.videoId;
a.O("nowAutoplaying",parseInt(b.params.timeout,10))},ssa=function(a,b){var c="true"==b.params.hasNext;
a.Ra.Pe="true"==b.params.hasPrevious;a.Ra.hasNext=c;a.O("previousNextChange")},jsa=function(a){g.kq(a.F);
a.F=g.iq((0,g.y)(a.Th,a,1),864E5)},P8=function(a,b,c){c?K8("Sending: action="+b+", params="+g.Gg(c)):K8("Sending: action="+b);
a.g.sendMessage(b,c)},Q8=function(a){Q7.call(this,"ScreenServiceProxy");
this.bd=a;this.i=[];this.i.push(this.bd.$_s("screenChange",(0,g.y)(this.XN,this)));this.i.push(this.bd.$_s("onlineScreenChange",(0,g.y)(this.EK,this)))},xsa=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.aq("MDX_CONFIG")||b;Aqa();b7();R8||(R8=new I7(b?b.loungeApiHost:void 0),Iqa()&&(R8.g="/api/loungedev"));S8||(S8=g.x("yt.mdx.remote.deferredProxies_")||[],g.Ga("yt.mdx.remote.deferredProxies_",S8,void 0));tsa();var c=T8();if(!c){var d=new Z7(R8);g.Ga("yt.mdx.remote.screenService_",d,void 0);c=T8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);Yra(a,d,function(m){m?U8()&&t8(U8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){N6("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.x("yt.mdx.remote.initialized_")&&(g.Ga("yt.mdx.remote.initialized_",!0,void 0),V8("Initializing: "+g.Gg(b)),W8.push(g.pq("yt-remote-cast2-availability-change",function(){N6("yt-remote-receiver-availability-change")})),W8.push(g.pq("yt-remote-cast2-receiver-selected",function(){X8(null);
N6("yt-remote-auto-connect","cast-selector-receiver")})),W8.push(g.pq("yt-remote-cast2-receiver-resumed",function(){N6("yt-remote-receiver-resumed","cast-selector-receiver")})),W8.push(g.pq("yt-remote-cast2-session-change",usa)),W8.push(g.pq("yt-remote-connection-change",function(m){m?t8(U8(),"YouTube TV"):Y8()||(t8(null,null),asa())})),a=Z8(),b.isAuto&&(a.id+="#dial"),g.Xq("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),V8(" -- with channel params: "+
g.Gg(a)),vsa(a),c.start(),U8()||wsa())},zsa=function(){var a=ysa();
q8()&&g.Qt("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},ysa=function(){var a=T8().bd.$_gos();
var b=$8();b&&a9()&&(W6(a,b)||a.push(b));return zqa(a)},b9=function(){var a=Asa();
!a&&q8()&&$ra()&&(a={key:"cast-selector-receiver",name:$ra()});return a},Asa=function(){var a=ysa(),b=$8();
b||(b=Y8());return g.Wa(a,function(c){return b&&Q6(b,c.key)?!0:!1})},$8=function(){var a=U8();
if(!a)return null;var b=T8().Td();return X6(b,a)},usa=function(a){V8("remote.onCastSessionChange_: "+T6(a));
if(a){var b=$8();b&&b.id==a.id?t8(b.id,"YouTube TV"):(b&&c9(),d9(a,1))}else a9()&&c9()},c9=function(){r8()?o8().stopSession():m8("stopSession called before API ready.");
var a=a9();a&&(a.disconnect(1),e9(null))},f9=function(){var a=a9();
return!!a&&3!=a.getProxyState()},V8=function(a){M7("remote",a)},T8=function(){if(!g9){var a=g.x("yt.mdx.remote.screenService_");
g9=a?new Q8(a):null}return g9},U8=function(){return g.x("yt.mdx.remote.currentScreenId_")},Bsa=function(a){g.Ga("yt.mdx.remote.currentScreenId_",a,void 0)},Csa=function(){return g.x("yt.mdx.remote.connectData_")},X8=function(a){g.Ga("yt.mdx.remote.connectData_",a,void 0)},a9=function(){return g.x("yt.mdx.remote.connection_")},e9=function(a){var b=a9();
X8(null);a||Bsa("");g.Ga("yt.mdx.remote.connection_",a,void 0);S8&&((0,g.B)(S8,function(c){c(a)}),S8.length=0);
b&&!a?N6("yt-remote-connection-change",!1):!b&&a&&N6("yt-remote-connection-change",!0)},Y8=function(){var a=g.Rt();
if(!a)return null;var b=T8().Td();return X6(b,a)},d9=function(a,b){$8()&&$8();
if(h9)i9=a;else{Bsa(a.id);var c=new J8(R8,a,Z8());c.connect(b,Csa());c.subscribe("beforeDisconnect",function(d){N6("yt-remote-before-disconnect",d)});
c.subscribe("beforeDispose",function(){a9()&&e9(null)});
e9(c)}},wsa=function(){var a=Y8();
a?(V8("Resume connection to: "+T6(a)),d9(a,0)):(c7(),asa(),V8("Skipping connecting because no session screen found."))},tsa=function(){var a=Z8();
if(g.Yb(a)){a=a7();var b=g.Qt("yt-remote-session-name")||"",c=g.Qt("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Ga("yt.mdx.remote.channelParams_",a,void 0)}},Z8=function(){return g.x("yt.mdx.remote.channelParams_")||{}},vsa=function(a){a?(g.Pt("yt-remote-session-app",a.app),g.Pt("yt-remote-session-name",a.name)):(Y6("yt-remote-session-app"),Y6("yt-remote-session-name"));
g.Ga("yt.mdx.remote.channelParams_",a,void 0)},j9=function(a,b,c){g.D.call(this);
this.A=a;this.i=b;this.l=new g.dt(this);g.G(this,this.l);this.l.L(b,"onCaptionsTrackListChanged",this.ZJ);this.l.L(b,"captionschanged",this.YI);this.l.L(b,"captionssettingschanged",this.hB);this.l.L(b,"videoplayerreset",this.ao);this.l.L(b,"mdxautoplaycancel",this.YC);this.R=this.l.L(b,"onVolumeChange",this.Az);this.F=!1;this.g=c;c.subscribe("proxyStateChange",this.Mz,this);c.subscribe("remotePlayerChange",this.Jk,this);c.subscribe("remoteQueueChange",this.ao,this);c.subscribe("autoplayUpNext",this.oz,
this);c.subscribe("previousNextChange",this.Jz,this);c.subscribe("nowAutoplaying",this.Fz,this);c.subscribe("autoplayDismissed",this.nz,this);this.suggestion=null;this.G=new g.ZC(64);this.o=new g.M(this.fB,500,this);g.G(this,this.o);this.B=new g.M(this.gB,1E3,this);g.G(this,this.B);this.J=new g7(this.CN,0,this);g.G(this,this.J);this.D={};this.T=new g.M(this.IB,1E3,this);g.G(this,this.T);this.I=new g.Il(this.uG,1E3,this);g.G(this,this.I);this.N=g.Ha;this.hB();this.ao();this.Jk()},k9=function(a,b){a.A.Pc(b,
a.i.getVideoData().lengthSeconds)},Dsa=function(a){k9(a,0);
a.o.stop();l9(a,new g.ZC(64))},n9=function(a,b){if(m9(a)&&!a.F){var c=null;
b&&(c={style:a.i.getSubtitlesUserSettings()},g.fc(c,b));a.g.WA(a.i.getVideoData(1).videoId,c);a.D=D8(a.g).g}},o9=function(a,b){var c=a.i.getPlaylist();
if(c){var d=c.Va;var e=c.listId.toString()}c=a.i.getVideoData(1);a.g.playVideo(c.videoId,b,d,e,c.playerParams,c.Re,I6(c));l9(a,new g.ZC(1))},Esa=function(a,b){if(b){var c=a.i.getOption("captions","tracklist",{zR:1});
c&&c.length?(a.i.setOption("captions","track",b),a.F=!1):(a.i.loadModule("captions"),a.F=!0)}else a.i.setOption("captions","track",{})},m9=function(a){return D8(a.g).videoId==a.i.getVideoData(1).videoId},l9=function(a,b){a.B.stop();
var c=a.G;if(!g.eD(c,b)){var d=g.U(b,2);d!=g.U(a.G,2)&&g.dL(a.i,d);a.G=b;Fsa(a.A,c,b)}},p9=function(){g.W.call(this,{C:"div",
H:"ytp-mdx-popup-dialog",M:{role:"dialog"},K:[{C:"div",H:"ytp-mdx-popup-dialog-inner-content",K:[{C:"div",H:"ytp-mdx-popup-title",V:"\ub85c\uadf8\uc544\uc6c3\ub418\uc5c8\uc2b5\ub2c8\ub2e4"},{C:"div",H:"ytp-mdx-popup-description",V:"\uc2dc\uccad\ud55c \ub3d9\uc601\uc0c1\uc774 TV\uc758 \uc2dc\uccad \uae30\ub85d\uc5d0 \ucd94\uac00\ub418\uc5b4 TV \ub9de\ucda4 \ub3d9\uc601\uc0c1\uc5d0 \uc601\ud5a5\uc744 \ubbf8\uce60 \uc218 \uc788\uc2b5\ub2c8\ub2e4. \uc6d0\ud558\uc9c0 \uc54a\uc73c\uba74 \ucde8\uc18c\ud558\uace0 \ucef4\ud4e8\ud130\uc5d0\uc11c YouTube\uc5d0 \ub85c\uadf8\uc778\ud558\uc138\uc694."},
{C:"div",H:"ytp-mdx-privacy-popup-buttons",K:[{C:"button",X:["ytp-button","ytp-mdx-privacy-popup-cancel"],V:"\ucde8\uc18c"},{C:"button",X:["ytp-button","ytp-mdx-privacy-popup-confirm"],V:"\ud655\uc778"}]}]}]});this.l=new g.YQ(this,250);g.G(this,this.l);this.D=this.i["ytp-mdx-privacy-popup-cancel"];this.L(this.D,"click",this.o);this.A=this.i["ytp-mdx-privacy-popup-confirm"];this.L(this.A,"click",this.B)},q9=function(a){g.W.call(this,{C:"div",
H:"ytp-remote",K:[{C:"div",H:"ytp-remote-display-status",K:[{C:"div",H:"ytp-remote-display-status-icon",K:[g.mQ()]},{C:"div",H:"ytp-remote-display-status-text",V:"{{statustext}}"}]}]});this.l=new g.YQ(this,250);g.G(this,this.l);this.o=a;this.L(a,"presentingplayerstatechange",this.A);Gsa(this,g.$K(a))},Gsa=function(a,b){if(3==a.o.getPresentingPlayerType()){var c={RECEIVER_NAME:a.o.getOption("remote","currentReceiver").name};
c=g.U(b,128)?g.lO("$RECEIVER_NAME\uc5d0\uc11c \uc624\ub958 \ubc1c\uc0dd",c):g.fD(b)||g.U(b,4)?g.lO("$RECEIVER_NAME\uc5d0\uc11c \uc7ac\uc0dd \uc911",c):g.lO("$RECEIVER_NAME\uc5d0 \uc5f0\uacb0\ub428",c);a.updateValue("statustext",c);a.l.show()}else a.l.hide()},r9=function(a,b){g.JU.call(this,"\uc7ac\uc0dd\ud560 \ud654\uba74:",0,a,b);
this.l=a;this.D={};this.L(a,"onMdxReceiversChange",this.J);this.L(a,"presentingplayerstatechange",this.J);this.J()},s9=function(a){g.EL.call(this,a);
this.i={key:V6(),name:"\uc774 \ucef4\ud4e8\ud130"};this.A=null;this.o=[];this.I=this.g=null;this.F=[this.i];this.l=this.i;this.tk=new g.ZC(64);this.J=0;this.Zm=-1;this.B=null;if(!g.yz(g.X(this.player))){a=this.player;var b=g.SD(a);b&&(b=b.Fn())&&(b=new r9(a,b),g.G(this,b));b=new q9(a);g.G(this,b);g.oL(a,b.element,4);this.B=new p9;g.G(this,this.B);g.oL(a,this.B.element,4);this.G=!!Y8()}this.D=null},t9=function(a){a.D&&(a.player.removeEventListener("presentingplayerstatechange",a.D),a.D=null)},Fsa=
function(a,b,c){a.tk=c;
a.player.O("presentingplayerstatechange",new g.jE(c,b))},u9=function(a,b){if(b.key!=a.l.key)if(b.key==a.i.key)c9();
else{var c;(c=!g.P(g.X(a.player).experiments,"mdx_enable_privacy_disclosure_ui"))||(c=((c=g.aq("PLAYER_CONFIG"))&&c.args&&void 0!==c.args.authuser?!0:!(!g.aq("SESSION_INDEX")&&!g.aq("LOGGED_IN")))||a.G||!a.B);c||g.yz(g.X(a.player))||(g.fD(g.$K(a.player))?a.player.pauseVideo():(a.D=(0,g.y)(a.DM,a),a.player.addEventListener("presentingplayerstatechange",a.D)),a.B&&a.B.l.show(),a9()||(h9=!0));a.l=b;var d=a.player.getPlaylistId();c=a.player.getVideoData(1);var e=c.videoId;if(d||e){var f=a.player.getPlaylist();
if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.va(l).videoId}else k=[e];f=a.player.getCurrentTime(1);d={videoIds:k,listId:d,videoId:e,playerParams:c.playerParams,clickTrackingParams:c.Re,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0==f?void 0:f};(c=I6(c))&&(d.locationInfo=c);c=d}else c=null;V8("Connecting to: "+g.Gg(b));"cast-selector-receiver"==b.key?(X8(c||null),r8()?o8().setLaunchParams(c||null):m8("setLaunchParams called before ready.")):!c&&f9()&&U8()==b.key?N6("yt-remote-connection-change",
!0):(c9(),X8(c||null),c=T8().Td(),(c=X6(c,b.key))&&d9(c,1))}},pqa=/^https?$/i,Hsa=["POST",
"PUT"];g.A(G6,g.Mf);g.h=G6.prototype;
g.h.send=function(a,b,c,d){if(this.g)throw Error("[goog.net.XhrIo] Object is active with another request="+this.F+"; newUri="+a);b=b?b.toUpperCase():"GET";this.F=a;this.l="";this.A=0;this.aa=b;this.R=!1;this.i=!0;this.g=this.N?y6(this.N):y6(g.MZ);this.T=this.N?this.N.getOptions():g.MZ.getOptions();this.g.onreadystatechange=(0,g.y)(this.Tw,this);try{v6(z6(this,"Opening Xhr")),this.ba=!0,this.g.open(b,String(a),!0),this.ba=!1}catch(f){v6(z6(this,"Error opening Xhr: "+f.message));D6(this,f);return}a=
c||"";var e=this.headers.clone();d&&mqa(d,function(f,k){e.set(k,f)});
d=g.Wa(e.Rd(),nqa);c=g.v.FormData&&a instanceof g.v.FormData;!g.$a(Hsa,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(f,k){this.g.setRequestHeader(k,f)},this);
this.Y&&(this.g.responseType=this.Y);"withCredentials"in this.g&&this.g.withCredentials!==this.U&&(this.g.withCredentials=this.U);try{A6(this),0<this.B&&(this.J=oqa(this.g),v6(z6(this,"Will abort after "+this.B+"ms if incomplete, xhr2 "+this.J)),this.J?(this.g.timeout=this.B,this.g.ontimeout=(0,g.y)(this.Uw,this)):this.G=g.Cg(this.Uw,this.B,this)),v6(z6(this,"Sending request")),this.D=!0,this.g.send(a),this.D=!1}catch(f){v6(z6(this,"Send error: "+f.message)),D6(this,f)}};
g.h.Uw=function(){"undefined"!=typeof g.qZ&&this.g&&(this.l="Timed out after "+this.B+"ms, aborting",this.A=8,z6(this,this.l),this.dispatchEvent("timeout"),this.abort(8))};
g.h.abort=function(a){this.g&&this.i&&(z6(this,"Aborting"),this.i=!1,this.o=!0,this.g.abort(),this.o=!1,this.A=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),C6(this))};
g.h.W=function(){this.g&&(this.i&&(this.i=!1,this.o=!0,this.g.abort(),this.o=!1),C6(this,!0));G6.gb.W.call(this)};
g.h.Tw=function(){this.ga()||(this.ba||this.D||this.o?F6(this):this.bL())};
g.h.bL=function(){F6(this)};
g.h.isActive=function(){return!!this.g};
g.h.getStatus=function(){try{return 2<E6(this)?this.g.status:-1}catch(a){return-1}};
g.h.getLastError=function(){return g.u(this.l)?this.l:String(this.l)};
var Vqa={"\x00":"\\0","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"\\u003C"},q7={"'":"\\'"},Isa={};g.h=M6.prototype;g.h.isEmpty=function(){return 0==this.g.length&&0==this.i.length};
g.h.clear=function(){this.g=[];this.i=[]};
g.h.contains=function(a){return g.$a(this.g,a)||g.$a(this.i,a)};
g.h.remove=function(a){var b=this.g;var c=(0,g.Xma)(b,a);0<=c?(g.bb(b,c),b=!0):b=!1;return b||g.cb(this.i,a)};
g.h.Dc=function(){for(var a=[],b=this.g.length-1;0<=b;--b)a.push(this.g[b]);var c=this.i.length;for(b=0;b<c;++b)a.push(this.i[b]);return a};
var xqa={xO:"atp",MQ:"ska",BQ:"que",cQ:"mus",LQ:"sus",uP:"dsp",IQ:"seq"};O6.prototype.kg=function(){var a=new O6({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.l=this.l;a.i=this.i;a.g=this.g};
var d7,$6="",Nqa=Jqa("loadCastFramework")||Jqa("loadCastApplicationFramework"),Xra=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];g.A(g7,g.D);g.h=g7.prototype;g.h.QD=function(a){this.o=arguments;this.g=!1;this.Ba?this.l=(0,g.H)()+this.cd:this.Ba=g.Cg(this.A,this.cd)};
g.h.stop=function(){this.Ba&&(g.v.clearTimeout(this.Ba),this.Ba=null);this.l=null;this.g=!1;this.o=[]};
g.h.pause=function(){++this.i};
g.h.resume=function(){this.i&&(--this.i,!this.i&&this.g&&(this.g=!1,this.B.apply(null,this.o)))};
g.h.W=function(){this.stop();g7.gb.W.call(this)};
g.h.RD=function(){this.l?(this.Ba=g.Cg(this.A,this.l-(0,g.H)()),this.l=null):(this.Ba=null,this.i?this.g=!0:(this.g=!1,this.B.apply(null,this.o)))};h7.prototype.stringify=function(a){return g.v.JSON.stringify(a,void 0)};
h7.prototype.parse=function(a){return g.v.JSON.parse(a,void 0)};g.h=i7.prototype;g.h.eh=null;g.h.Fe=!1;g.h.aj=null;g.h.Tt=null;g.h.Ki=null;g.h.di=null;g.h.cg=null;g.h.Gg=null;g.h.wh=null;g.h.wc=null;g.h.sl=0;g.h.Je=null;g.h.Ro=null;g.h.sg=null;g.h.Wj=-1;g.h.KA=!0;g.h.Rg=!1;g.h.Lq=0;g.h.mo=null;var Tqa={},l7={};g.h=i7.prototype;g.h.setTimeout=function(a){this.o=a};
g.h.OM=function(a){a=a.target;var b=this.mo;b&&3==E6(a)?b.Sj():this.QB(a)};
g.h.QB=function(a){try{if(a==this.wc)a:{var b=E6(this.wc),c=this.wc.A,d=this.wc.getStatus();if(g.Ld&&!g.nd(10)||g.Nd&&!g.md("420+")){if(4>b)break a}else if(3>b||3==b&&!g.xh&&!H6(this.wc))break a;this.Rg||4!=b||7==c||(8==c||0>=d?this.g.Ce(3):this.g.Ce(2));s7(this);var e=this.wc.getStatus();this.Wj=e;var f=H6(this.wc);(this.Fe=200==e)?(4==b&&o7(this),this.A?(Uqa(this,b,f),g.xh&&this.Fe&&3==b&&(this.da.ea(this.i,"tick",this.HM),this.i.start())):n7(this,f),this.Fe&&!this.Rg&&(4==b?this.g.Xn(this):(this.Fe=
!1,k7(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.sg=3,m7(13)):(this.sg=0,m7(14)),o7(this),p7(this))}}catch(k){this.wc&&H6(this.wc)}finally{}};
g.h.HM=function(){var a=E6(this.wc),b=H6(this.wc);this.sl<b.length&&(s7(this),Uqa(this,a,b),this.Fe&&4!=a&&k7(this))};
g.h.cM=function(a){r7((0,g.y)(this.bM,this,a),0)};
g.h.bM=function(a){this.Rg||(s7(this),n7(this,a),k7(this))};
g.h.Tz=function(a){r7((0,g.y)(this.aM,this,a),0)};
g.h.aM=function(a){this.Rg||(o7(this),this.Fe=a,this.g.Xn(this),this.g.Ce(4))};
g.h.cancel=function(){this.Rg=!0;o7(this)};
g.h.mM=function(){this.aj=null;var a=(0,g.H)();0<=a-this.Tt?(2!=this.di&&this.g.Ce(3),o7(this),this.sg=2,m7(18),p7(this)):Xqa(this,this.Tt-a)};
g.h.getLastError=function(){return this.sg};g.h=$qa.prototype;g.h.Jq=null;g.h.Id=null;g.h.no=!1;g.h.Sw=null;g.h.qm=null;g.h.xr=null;g.h.Kq=null;g.h.je=null;g.h.Df=-1;g.h.Vj=null;g.h.pj=null;g.h.connect=function(a){this.Kq=a;a=u7(this.g,null,this.Kq);m7(3);this.Sw=(0,g.H)();var b=this.g.F;null!=b?(this.Vj=b[0],(this.pj=b[1])?(this.je=1,ara(this)):(this.je=2,w7(this))):(x6(a,"MODE","init"),this.Id=new i7(this,void 0,void 0,void 0),this.Id.eh=this.Jq,j7(this.Id,a,!1,null,!0),this.je=0)};
g.h.ZC=function(a){if(a)this.je=2,w7(this);else{m7(4);var b=this.g;b.Oe=b.jg.Df;D7(b,9)}a&&this.Ce(2)};
g.h.eq=function(a){return this.g.eq(a)};
g.h.abort=function(){this.Id&&(this.Id.cancel(),this.Id=null);this.Df=-1};
g.h.Rw=function(){return!1};
g.h.Nz=function(a,b){this.Df=a.Wj;if(0==this.je)if(b){try{var c=this.i.parse(b)}catch(d){c=this.g;c.Oe=this.Df;D7(c,2);return}this.Vj=c[0];this.pj=c[1]}else c=this.g,c.Oe=this.Df,D7(c,2);else if(2==this.je)if(this.no)m7(7),this.xr=(0,g.H)();else if("11111"==b){if(m7(6),this.no=!0,this.qm=(0,g.H)(),c=this.qm-this.Sw,!g.Ld||g.nd(10)||500>c)this.Df=200,this.Id.cancel(),m7(12),v7(this.g,this,!0)}else m7(8),this.qm=this.xr=(0,g.H)(),this.no=!1};
g.h.Xn=function(){this.Df=this.Id.Wj;if(this.Id.Fe)0==this.je?this.pj?(this.je=1,ara(this)):(this.je=2,w7(this)):2==this.je&&((!g.Ld||g.nd(10)?!this.no:200>this.xr-this.qm)?(m7(11),v7(this.g,this,!1)):(m7(12),v7(this.g,this,!0)));else{0==this.je?m7(9):2==this.je&&m7(10);var a=this.g;this.Id.getLastError();a.Oe=this.Df;D7(a,2)}};
g.h.al=function(){return this.g.al()};
g.h.isActive=function(){return this.g.isActive()};
g.h.Ce=function(a){this.g.Ce(a)};g.h=x7.prototype;g.h.Dj=null;g.h.Fd=null;g.h.Ub=null;g.h.Iq=null;g.h.sm=null;g.h.av=null;g.h.Hm=null;g.h.Ek=0;g.h.qI=0;g.h.Yc=null;g.h.qg=null;g.h.sf=null;g.h.Wg=null;g.h.jg=null;g.h.Po=null;g.h.pi=-1;g.h.Ix=-1;g.h.Oe=-1;g.h.Wh=0;g.h.Ph=0;g.h.Sg=8;var E7=new g.Mf;g.A(cra,g.of);g.A(dra,g.of);g.A(era,g.of);g.h=x7.prototype;g.h.connect=function(a,b,c,d,e){m7(0);this.Iq=b;this.Dj=c||{};d&&g.Da(e)&&(this.Dj.OSID=d,this.Dj.OAID=e);this.B?(r7((0,g.y)(this.Av,this,a),100),ira(this)):this.Av(a)};
g.h.Av=function(a){this.jg=new $qa(this);this.jg.Jq=null;this.jg.i=this.A;this.jg.connect(a)};
g.h.Rw=function(){return 0==this.g};
g.h.Sz=function(a){this.qg=null;lra(this,a)};
g.h.Rz=function(){this.sf=null;this.Ub=new i7(this,this.l,"rpc",this.D);this.Ub.eh=null;this.Ub.Lq=0;var a=this.av.clone();g.sn(a,"RID","rpc");g.sn(a,"SID",this.l);g.sn(a,"CI",this.Po?"0":"1");g.sn(a,"AID",this.pi);y7(this,a);if(!g.Ld||g.nd(10))g.sn(a,"TYPE","xmlhttp"),j7(this.Ub,a,!0,this.Hm,!1);else{g.sn(a,"TYPE","html");var b=this.Ub,c=!!this.Hm;b.di=3;b.cg=w6(a.clone());Wqa(b,c)}};
g.h.Nz=function(a,b){if(0!=this.g&&(this.Ub==a||this.Fd==a))if(this.Oe=a.Wj,this.Fd==a&&3==this.g)if(7<this.Sg){try{var c=this.A.parse(b)}catch(f){c=null}if(g.Ka(c)&&3==c.length)if(0==c[0])a:{if(!this.sf){if(this.Ub)if(this.Ub.Ki+3E3<this.Fd.Ki)A7(this),this.Ub.cancel(),this.Ub=null;else break a;C7(this);m7(19)}}else this.Ix=c[1],0<this.Ix-this.pi&&37500>c[2]&&this.Po&&0==this.Ph&&!this.Wg&&(this.Wg=r7((0,g.y)(this.UI,this),6E3));else D7(this,11)}else b!=Isa.VO.g&&D7(this,11);else if(this.Ub==a&&
A7(this),!g.wb(b)){c=this.A.parse(b);g.Ka(c);for(var d=0;d<c.length;d++){var e=c[d];this.pi=e[0];e=e[1];2==this.g?"c"==e[0]?(this.l=e[1],this.Hm=e[2],e=e[3],null!=e?this.Sg=e:this.Sg=6,this.g=3,this.Yc&&this.Yc.uv(),this.av=u7(this,this.al()?this.Hm:null,this.Iq),mra(this)):"stop"==e[0]&&D7(this,7):3==this.g&&("stop"==e[0]?D7(this,7):"noop"!=e[0]&&this.Yc&&this.Yc.tv(e),this.Ph=0)}}};
g.h.UI=function(){null!=this.Wg&&(this.Wg=null,this.Ub.cancel(),this.Ub=null,C7(this),m7(20))};
g.h.Xn=function(a){if(this.Ub==a){A7(this);this.Ub=null;var b=2}else if(this.Fd==a)this.Fd=null,b=1;else return;this.Oe=a.Wj;if(0!=this.g)if(a.Fe)1==b?(b=(0,g.H)()-a.Ki,E7.dispatchEvent(new dra(E7,a.wh?a.wh.length:0,b,this.Wh)),z7(this),this.o.length=0):mra(this);else{var c=a.getLastError(),d;if(!(d=3==c||7==c||0==c&&0<this.Oe)){if(d=1==b)this.Fd||this.qg||1==this.g||2<=this.Wh?d=!1:(this.qg=r7((0,g.y)(this.Sz,this,a),nra(this,this.Wh)),this.Wh++,d=!0);d=!(d||2==b&&C7(this))}if(d)switch(c){case 1:D7(this,
5);break;case 4:D7(this,10);break;case 3:D7(this,6);break;case 7:D7(this,12);break;default:D7(this,2)}}};
g.h.rD=function(a){if(!g.$a(arguments,this.g))throw Error("Unexpected channel state: "+this.g);};
g.h.tN=function(a){a?m7(2):(m7(1),ora(this,8))};
g.h.eq=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new G6;a.U=!1;return a};
g.h.isActive=function(){return!!this.Yc&&this.Yc.isActive(this)};
g.h.Ce=function(a){E7.dispatchEvent(new era(E7,a))};
g.h.al=function(){return!(!g.Ld||g.nd(10))};
g.h=pra.prototype;g.h.uv=function(){};
g.h.tv=function(){};
g.h.qv=function(){};
g.h.Op=function(){};
g.h.rw=function(){return{}};
g.h.isActive=function(){return!0};g.A(F7,g.D);g.h=F7.prototype;g.h.UL=function(){this.cd=Math.min(3E5,2*this.cd);this.l();this.i&&this.start()};
g.h.start=function(){var a=this.cd+15E3*Math.random();g.Ao(this.g,a);this.i=(0,g.H)()+a};
g.h.stop=function(){this.g.stop();this.i=0};
g.h.isActive=function(){return this.g.isActive()};
g.h.reset=function(){this.g.stop();this.cd=5E3};g.A(G7,pra);g.h=G7.prototype;g.h.subscribe=function(a,b,c){return this.l.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.l.unsubscribe(a,b,c)};
g.h.Mf=function(a){return this.l.fh(a)};
g.h.O=function(a,b){return this.l.O.apply(this.l,arguments)};
g.h.dispose=function(){this.kb||(this.kb=!0,g.mf(this.l),sra(this),g.mf(this.i),this.i=null)};
g.h.ga=function(){return this.kb};
g.h.connect=function(a,b,c){if(!this.g||2!=this.g.g){this.G="";this.i.stop();this.A=a||null;this.o=b||0;a=this.I+"/test";b=this.I+"/bind";var d=new x7(c?c.firstTestResults:null,c?c.secondTestResults:null,this.J),e=this.g;e&&(e.Yc=null);d.Yc=this;this.g=d;e?this.g.connect(a,b,this.B,e.l,e.pi):c?this.g.connect(a,b,this.B,c.sessionId,c.arrayId):this.g.connect(a,b,this.B)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.fc(c,b);this.i.isActive()||2==(this.g?this.g.g:0)?this.D.push(c):H7(this)&&jra(this.g,c)};
g.h.uv=function(){this.i.reset();this.A=null;this.o=0;if(this.D.length){var a=this.D;this.D=[];for(var b=0,c=a.length;b<c;++b)jra(this.g,a[b])}this.O("handlerOpened")};
g.h.qv=function(a){var b=2==a&&401==this.g.Oe;4==a||b||this.i.start();this.O("handlerError",a)};
g.h.Op=function(a){if(!this.i.isActive())this.O("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.D.push(d)}};
g.h.rw=function(){var a={v:2};this.G&&(a.gsessionid=this.G);0!=this.o&&(a.ui=""+this.o);0!=this.F&&(a.ui=""+this.F);this.A&&g.fc(a,this.A);return a};
g.h.tv=function(a){"S"==a[0]?this.G=a[1]:"gracefulReconnect"==a[0]?(this.i.start(),hra(this.g)):this.O("handlerMessage",new qra(a[0],a[1]))};
g.h.YM=function(){this.i.isActive();var a=this.g,b=0;a.Ub&&b++;a.Fd&&b++;0==b&&this.connect(this.A,this.o)};I7.prototype.o=function(a,b,c,d){b?a(d):a({text:c.responseText})};
I7.prototype.l=function(a,b){a(Error("Request error: "+b.status))};
I7.prototype.A=function(a){a(Error("request timed out"))};var Ara=(0,g.H)(),L7=null,O7=Array(50),N7=-1,P7=!1;g.A(Q7,g.O);Q7.prototype.Td=function(){return this.g};
Q7.prototype.contains=function(a){return!!W6(this.g,a)};
Q7.prototype.get=function(a){return a?X6(this.g,a):null};
Q7.prototype.info=function(a){M7(this.D,a)};g.t(R7,g.O);g.h=R7.prototype;g.h.start=function(){!this.g&&isNaN(this.Ba)&&this.TB()};
g.h.stop=function(){this.g&&(this.g.abort(),this.g=null);isNaN(this.Ba)||(g.kq(this.Ba),this.Ba=NaN)};
g.h.W=function(){this.stop();g.O.prototype.W.call(this)};
g.h.TB=function(){this.Ba=NaN;this.g=g.fr(J7(this.B,"/pairing/get_screen"),{method:"POST",wb:{pairing_code:this.A},timeout:5E3,onSuccess:(0,g.y)(this.VN,this),onError:(0,g.y)(this.UN,this),re:(0,g.y)(this.WN,this)})};
g.h.VN=function(a,b){this.g=null;var c=b.screen||{};c.dialId=this.l;c.name=this.o;this.O("pairingComplete",new P6(c))};
g.h.UN=function(a){this.g=null;a.status&&404==a.status?this.i>=Jsa.length?this.O("pairingFailed",Error("DIAL polling timed out")):(a=Jsa[this.i],this.Ba=g.iq((0,g.y)(this.TB,this),a),this.i++):this.O("pairingFailed",Error("Server error "+a.status))};
g.h.WN=function(){this.g=null;this.O("pairingFailed",Error("Server not responding"))};
var Jsa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.A(T7,Q7);g.h=T7.prototype;g.h.start=function(){S7(this)&&this.O("screenChange");!g.Qt("yt-remote-lounge-token-expiration")&&Era(this);g.kq(this.i);this.i=g.iq((0,g.y)(this.start,this),1E4)};
g.h.add=function(a,b){S7(this);Bra(this,a);U7(this,!1);this.O("screenChange");b(a);a.token||Era(this)};
g.h.remove=function(a,b){var c=S7(this);Dra(this,a)&&(U7(this,!1),c=!0);b(a);c&&this.O("screenChange")};
g.h.Lo=function(a,b,c,d){var e=S7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,U7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.O("screenChange")};
g.h.W=function(){g.kq(this.i);T7.gb.W.call(this)};
g.h.bE=function(a){S7(this);var b=this.g.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}U7(this,!b);b&&M7(this.D,"Missed "+b+" lounge tokens.")};
g.h.aE=function(a){M7(this.D,"Requesting lounge tokens failed: "+a)};g.t(W7,g.O);g.h=W7.prototype;g.h.start=function(){var a=parseInt(g.Qt("yt-remote-fast-check-period")||"0",10);(this.o=(0,g.H)()-144E5<a?0:a)?Y7(this):(this.o=(0,g.H)()+3E5,g.Pt("yt-remote-fast-check-period",this.o),this.Vs())};
g.h.isEmpty=function(){return g.Yb(this.g)};
g.h.update=function(){V7("Updating availability on schedule.");var a=this.B(),b=g.Lb(this.g,function(c,d){return c&&!!X6(a,d)},this);
X7(this,b)};
g.h.W=function(){g.kq(this.l);this.l=NaN;this.i&&(this.i.abort(),this.i=null);g.O.prototype.W.call(this)};
g.h.Vs=function(){g.kq(this.l);this.l=NaN;this.i&&this.i.abort();var a=Hra(this);if(J6(a)){var b=J7(this.A,"/pairing/get_screen_availability");this.i=K7(this.A,b,{lounge_token:g.Rb(a).join(",")},(0,g.y)(this.xL,this,a),(0,g.y)(this.wL,this))}else X7(this,{}),Y7(this)};
g.h.xL=function(a,b){this.i=null;var c=g.Rb(Hra(this));if(g.rb(c,g.Rb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;X7(this,d);Y7(this)}else this.Kb("Changing Screen set during request."),this.Vs()};
g.h.wL=function(a){this.Kb("Screen availability failed: "+a);this.i=null;Y7(this)};
g.h.Kb=function(a){M7("OnlineScreenService",a)};g.A(Z7,Q7);g.h=Z7.prototype;g.h.start=function(){this.l.start();this.i.start();this.g.length&&(this.O("screenChange"),this.i.isEmpty()||this.O("onlineScreenChange"))};
g.h.add=function(a,b,c){this.l.add(a,b,c)};
g.h.remove=function(a,b,c){this.l.remove(a,b,c);this.i.update()};
g.h.Lo=function(a,b,c,d){this.l.contains(a)?this.l.Lo(a,b,c,d):(a="Updating name of unknown screen: "+a.name,M7(this.D,a),d(Error(a)))};
g.h.Td=function(a){return a?this.g:g.eb(this.g,(0,g.Xd)(this.o,function(b){return!this.contains(b)},this))};
g.h.UB=function(){return(0,g.Xd)(this.Td(!0),function(a){return!!this.i.g[a.id]},this)};
g.h.VB=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new R7(this.B,a,b,c);f.subscribe("pairingComplete",(0,g.y)(function(k){g.mf(f);d($7(this,k))},this));
f.subscribe("pairingFailed",function(k){g.mf(f);e(k)});
f.start();return(0,g.y)(f.stop,f)};
g.h.YN=function(a,b,c,d){g.fr(J7(this.B,"/pairing/get_screen"),{method:"POST",wb:{pairing_code:a},timeout:5E3,onSuccess:(0,g.y)(function(e,f){var k=new P6(f.screen||{});if(!k.name||Lra(this,k.name)){a:{var l=k.name;for(var m=2,n=b(l,m);Lra(this,n);){m++;if(20<m)break a;n=b(l,m)}l=n}k.name=l}c($7(this,k))},this),
onError:(0,g.y)(function(e){d(Error("pairing request failed: "+e.status))},this),
re:(0,g.y)(function(){d(Error("pairing request timed out."))},this)})};
g.h.W=function(){g.mf(this.l);g.mf(this.i);Z7.gb.W.call(this)};
g.h.jE=function(){Mra(this);this.O("screenChange");this.i.update()};
Z7.prototype.dispose=Z7.prototype.dispose;g.A(b8,g.O);g.h=b8.prototype;g.h.Zn=function(a){this.l=a;this.O("sessionScreen",this.l)};
g.h.Wd=function(a){this.ga()||(a&&c8(this,""+a),this.l=null,this.O("sessionScreen",null))};
g.h.info=function(a){M7(this.T,a)};
g.h.XB=function(){return null};
g.h.kt=function(a){var b=this.i;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.y)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.y)(function(){c8(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.W=function(){this.kt("");b8.gb.W.call(this)};g.A(d8,b8);g.h=d8.prototype;g.h.jt=function(a){if(this.g){if(this.g==a)return;c8(this,"Overriding cast sesison with new session object");this.g.removeUpdateListener(this.B);this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.A)}this.g=a;this.g.addUpdateListener(this.B);this.g.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.A);Ora(this)};
g.h.si=function(a){this.info("launchWithParams no-op for Cast: "+g.Gg(a))};
g.h.stop=function(){this.g?this.g.stop((0,g.y)(function(){this.Wd()},this),(0,g.y)(function(){this.Wd(Error("Failed to stop receiver app."))},this)):this.Wd(Error("Stopping cast device witout session."))};
g.h.kt=g.Ha;g.h.W=function(){this.info("disposeInternal");g.kq(this.o);this.o=0;this.g&&(this.g.removeUpdateListener(this.B),this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.A));this.g=null;d8.gb.W.call(this)};
g.h.xM=function(a,b){if(!this.ga())if(b){var c=L6(b);if(g.Na(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.Gg(c));switch(d){case "mdxSessionStatus":Nra(this,c.screenId);break;default:c8(this,"Unknown youtube message: "+d)}}else c8(this,"Unable to parse message.")}else c8(this,"No data in message.")};
g.h.Jw=function(a,b,c,d){Kra(this.G,this.i.label,a,this.i.friendlyName,(0,g.y)(function(e){e?b(e):0<=d?(c8(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.iq((0,g.y)(this.Jw,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.XB=function(){return this.g};
g.h.ZN=function(a){this.ga()||a||(c8(this,"Cast session died."),this.Wd())};g.A(e8,b8);g.h=e8.prototype;g.h.jt=function(a){this.o=a;this.o.addUpdateListener(this.J)};
g.h.si=function(a){this.A=a;this.D()};
g.h.stop=function(){this.g();this.g=g.Ha;g.kq(this.B);this.o?this.o.stop((0,g.y)(this.Wd,this,null),(0,g.y)(this.Wd,this,"Failed to stop DIAL device.")):this.Wd()};
g.h.W=function(){this.g();this.g=g.Ha;g.kq(this.B);this.o&&this.o.removeUpdateListener(this.J);this.o=null;e8.gb.W.call(this)};
g.h.cO=function(a){this.ga()||a||(c8(this,"DIAL session died."),this.g(),this.g=g.Ha,this.Wd())};
g.h.Yq=function(a){this.I=V6();if(this.A){var b=new chrome.cast.DialLaunchResponse(!0,Qra(this));a(b);Pra(this)}else this.D=(0,g.y)(function(){g.kq(this.B);this.D=g.Ha;this.B=NaN;var c=new chrome.cast.DialLaunchResponse(!0,Qra(this));a(c);Pra(this)},this),this.B=g.iq((0,g.y)(function(){this.D()},this),100)};
g.h.GE=function(a,b,c){Kra(this.G,this.F.receiver.label,a,this.i.friendlyName,(0,g.y)(function(d){d&&d.token?(this.Zn(d),b(new chrome.cast.DialLaunchResponse(!1))):this.Yq(b,c)},this),(0,g.y)(function(d){c8(this,"Failed to get DIAL screen: "+d);
this.Yq(b,c)},this))};g.A(f8,b8);f8.prototype.stop=function(){this.Wd()};
f8.prototype.jt=g.Ha;f8.prototype.si=function(){g.kq(this.g);this.g=NaN;var a=X6(this.G.Td(),this.i.label);a?this.Zn(a):this.Wd(Error("No such screen"))};
f8.prototype.W=function(){g.kq(this.g);this.g=NaN;f8.gb.W.call(this)};g.A(g8,g.O);g.h=g8.prototype;
g.h.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.D);this.F||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION,f=(0,g.y)(this.gL,this);c=new chrome.cast.ApiConfig(c,(0,g.y)(this.Pz,this),f,d,e);c.customDialLaunchCallback=(0,g.y)(this.uJ,this);chrome.cast.initialize(c,(0,g.y)(function(){this.ga()||
(chrome.cast.addReceiverActionListener(this.o),xra(),this.i.subscribe("onlineScreenChange",(0,g.y)(this.WB,this)),this.l=Sra(this),chrome.cast.setCustomReceivers(this.l,g.Ha,(0,g.y)(function(k){this.Kb("Failed to set initial custom receivers: "+g.Gg(k))},this)),this.O("yt-remote-cast2-availability-change",i8(this)),b(!0))},this),(0,g.y)(function(k){this.Kb("Failed to initialize API: "+g.Gg(k));
b(!1)},this))};
g.h.hN=function(a,b){h8("Setting connected screen ID: "+a+" -> "+b);if(this.g){var c=this.g.l;if(!a||c&&c.id!=a)h8("Unsetting old screen status: "+this.g.i.friendlyName),j8(this,null)}if(a&&b){if(!this.g){c=X6(this.i.Td(),a);if(!c){h8("setConnectedScreenStatus: Unknown screen.");return}var d=Rra(this,c);d||(h8("setConnectedScreenStatus: Connected receiver not custom..."),d=new chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=chrome.cast.ReceiverType.CUSTOM,this.l.push(d),chrome.cast.setCustomReceivers(this.l,
g.Ha,(0,g.y)(function(e){this.Kb("Failed to set initial custom receivers: "+g.Gg(e))},this)));
h8("setConnectedScreenStatus: new active receiver: "+d.friendlyName);j8(this,new f8(this.i,d),!0)}this.g.kt(b)}else h8("setConnectedScreenStatus: no screen.")};
g.h.iN=function(a){this.ga()?this.Kb("Setting connection data on disposed cast v2"):this.g?this.g.si(a):this.Kb("Setting connection data without a session")};
g.h.bO=function(){this.ga()?this.Kb("Stopping session on disposed cast v2"):this.g?(this.g.stop(),j8(this,null)):h8("Stopping non-existing session")};
g.h.requestSession=function(){chrome.cast.requestSession((0,g.y)(this.Pz,this),(0,g.y)(this.DL,this))};
g.h.W=function(){this.i.unsubscribe("onlineScreenChange",(0,g.y)(this.WB,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.o);g.cb(g.x("yt.mdx.remote.debug.handlers_")||[],ura);g.mf(this.g);g8.gb.W.call(this)};
g.h.Kb=function(a){M7("Controller",a)};
g.h.Qz=function(a,b){this.g==a&&(b||j8(this,null),this.O("yt-remote-cast2-session-change",b))};
g.h.cL=function(a,b){if(!this.ga())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),h8("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.g)if(this.g.i.label!=a.label)h8("onReceiverAction_: Stopping active receiver: "+this.g.i.friendlyName),this.g.stop();else{h8("onReceiverAction_: Casting to active receiver.");this.g.l&&this.O("yt-remote-cast2-session-change",this.g.l);break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:j8(this,
new f8(this.i,a));break;case chrome.cast.ReceiverType.DIAL:j8(this,new e8(this.i,a,this.B));break;case chrome.cast.ReceiverType.CAST:j8(this,new d8(this.i,a));break;default:this.Kb("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.g&&this.g.i.label==a.label?this.g.stop():this.Kb("Stopping receiver w/o session: "+a.friendlyName)}else this.Kb("onReceiverAction_ called without receiver.")};
g.h.uJ=function(a){if(this.ga())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.Kb("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.g?this.g.i:null;if(!c||c.label!=b.label)return this.Kb("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.g.l)return h8("Reselecting dial screen."),
this.O("yt-remote-cast2-session-change",this.g.l),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.Kb('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);j8(this,new e8(this.i,b,this.B))}b=this.g;b.F=a;return b.F.appState==chrome.cast.DialAppState.RUNNING?new Promise((0,g.y)(b.GE,b,(b.F.extraData||{}).screenId||null)):new Promise((0,g.y)(b.Yq,b))};
g.h.Pz=function(a){if(!this.ga()){h8("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.g)if(b.receiverType==chrome.cast.ReceiverType.CAST)h8("Got resumed cast session before resumed mdx connection."),b.friendlyName=chrome.cast.unescape(b.friendlyName),j8(this,new d8(this.i,b),!0);else{this.Kb("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.g.i,d=X6(this.i.Td(),c.label);d&&Q6(d,b.label)&&
c.receiverType!=chrome.cast.ReceiverType.CAST&&b.receiverType==chrome.cast.ReceiverType.CAST&&(h8("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.mf(this.g),this.g=new d8(this.i,b),this.g.subscribe("sessionScreen",(0,g.y)(this.Qz,this,this.g)),this.g.si(null));this.g.jt(a)}}};
g.h.aO=function(){return this.g?this.g.XB():null};
g.h.DL=function(a){this.ga()||(this.Kb("Failed to estabilish a session: "+g.Gg(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&j8(this,null))};
g.h.gL=function(a){h8("Receiver availability updated: "+a);if(!this.ga()){var b=i8(this);this.A=a==chrome.cast.ReceiverAvailability.AVAILABLE;i8(this)!=b&&this.O("yt-remote-cast2-availability-change",i8(this))}};
g.h.WB=function(){this.ga()||(this.l=Sra(this),h8("Updating custom receivers: "+g.Gg(this.l)),chrome.cast.setCustomReceivers(this.l,g.Ha,(0,g.y)(function(){this.Kb("Failed to set custom receivers.")},this)),this.O("yt-remote-cast2-availability-change",i8(this)))};
g8.prototype.setLaunchParams=g8.prototype.iN;g8.prototype.setConnectedScreenStatus=g8.prototype.hN;g8.prototype.stopSession=g8.prototype.bO;g8.prototype.getCastSession=g8.prototype.aO;g8.prototype.requestSession=g8.prototype.requestSession;g8.prototype.init=g8.prototype.init;g8.prototype.dispose=g8.prototype.dispose;var p8=[];u8.prototype.reset=function(a){this.listId="";this.index=-1;this.videoId="";v8(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.g=a.trackData,this.Pe=a.hasPrevious,this.hasNext=a.hasNext,this.D=a.playerTime,this.B=a.playerTimeAt,this.o=a.seekableStart,this.i=a.seekableEnd,this.F=a.duration,this.G=a.loadedTime,this.l=a.liveIngestionTime,this.A=
!isNaN(this.l))};
u8.prototype.isAdPlaying=function(){return 1081==this.playerState};
u8.prototype.getDuration=function(){return this.A?this.F+w8(this):this.F};
u8.prototype.clone=function(){return new u8(A8(this))};g.t(C8,g.O);g.h=C8.prototype;g.h.play=function(){1==this.g?(this.i?this.i.play(null,g.Ha,I8(this,"play")):H8(this,"play"),G8(this,1,y8(D8(this))),this.O("remotePlayerChange")):E8(this,this.play)};
g.h.pause=function(){1==this.g?(this.i?this.i.pause(null,g.Ha,I8(this,"pause")):H8(this,"pause"),G8(this,2,y8(D8(this))),this.O("remotePlayerChange")):E8(this,this.pause)};
g.h.seekTo=function(a){if(1==this.g){if(this.i){var b=D8(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=1==b.playerState||3==b.playerState?chrome.cast.media.ResumeState.PLAYBACK_START:chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.i.seek(c,g.Ha,I8(this,"seekTo",{newTime:a}))}else H8(this,"seekTo",{newTime:a});G8(this,3,a);this.O("remotePlayerChange")}else E8(this,g.Qa(this.seekTo,a))};
g.h.stop=function(){if(1==this.g){this.i?this.i.stop(null,g.Ha,I8(this,"stopVideo")):H8(this,"stopVideo");var a=D8(this);a.index=-1;a.videoId="";v8(a);F8(this,a);this.O("remotePlayerChange")}else E8(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.g){var c=D8(this);if(this.l){if(c.volume!=a){var d=Math.round(a)/100;this.l.setReceiverVolumeLevel(d,(0,g.y)(function(){M7("CP","set receiver volume: "+d)},this),(0,g.y)(function(){this.Kb("failed to set receiver volume.")},this))}c.muted!=b&&this.l.setReceiverMuted(b,(0,g.y)(function(){M7("CP","set receiver muted: "+b)},this),(0,g.y)(function(){this.Kb("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);H8(this,"setVolume",e)}c.muted=b;c.volume=a;F8(this,c)}else E8(this,g.Qa(this.setVolume,a,b))};
g.h.WA=function(a,b){if(1==this.g){var c=D8(this),d={videoId:a};b&&(c.g={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},d.style=g.Gg(b.style),g.fc(d,c.g));H8(this,"setSubtitlesTrack",d);F8(this,c)}else E8(this,g.Qa(this.WA,a,b))};
g.h.setAudioTrack=function(a,b){if(1==this.g){var c=b.getLanguageInfo().getId();H8(this,"setAudioTrack",{videoId:a,audioTrackId:c});var d=D8(this);d.audioTrackId=c;F8(this,d)}else E8(this,g.Qa(this.setAudioTrack,a,b))};
g.h.playVideo=function(a,b,c,d,e,f,k){var l=D8(this);c=c||0;var m={videoId:a,currentIndex:c};z8(l,a,c);g.Da(b)&&(x8(l,b),m.currentTime=b);g.Da(d)&&(m.listId=d);null!=e&&(m.playerParams=e);null!=f&&(m.clickTrackingParams=f);null!=k&&(m.locationInfo=g.Gg(k));H8(this,"setPlaylist",m);d||F8(this,l)};
g.h.fo=function(a,b){if(1==this.g){if(a&&b){var c=D8(this);z8(c,a,b);F8(this,c)}H8(this,"previous")}else E8(this,g.Qa(this.fo,a,b))};
g.h.nextVideo=function(a,b){if(1==this.g){if(a&&b){var c=D8(this);z8(c,a,b);F8(this,c)}H8(this,"next")}else E8(this,g.Qa(this.nextVideo,a,b))};
g.h.Sv=function(){1==this.g?H8(this,"dismissAutoplay"):E8(this,this.Sv)};
g.h.dispose=function(){if(3!=this.g){var a=this.g;this.g=3;this.O("proxyStateChange",a,this.g)}g.O.prototype.dispose.call(this)};
g.h.W=function(){esa(this);this.o=null;this.A.clear();B8(this,null);g.O.prototype.W.call(this)};
g.h.Wt=function(a){if((a!=this.g||2==a)&&3!=this.g&&0!=a){var b=this.g;this.g=a;this.O("proxyStateChange",b,a);if(1==a)for(;!this.A.isEmpty();)b=a=this.A,0==b.g.length&&(b.g=b.i,b.g.reverse(),b.i=[]),a.g.pop().apply(this);else 3==a&&this.dispose()}};
g.h.ZK=function(a,b){this.O(a,b)};
g.h.aJ=function(a){if(!a)this.Hk(null),B8(this,null);else if(this.l.receiver.volume){a=this.l.receiver.volume;var b=D8(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)M7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,F8(this,b)}};
g.h.Hk=function(a){M7("CP","Cast media: "+!!a);this.i&&this.i.removeUpdateListener(this.F);if(this.i=a)this.i.addUpdateListener(this.F),fsa(this),this.O("remotePlayerChange")};
g.h.ZI=function(a){a?(fsa(this),this.O("remotePlayerChange")):this.Hk(null)};
g.h.Ht=function(){H8(this,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.nJ=function(){var a=bsa();a&&B8(this,a)};
g.h.Kb=function(a){M7("CP",a)};g.t(J8,g.O);g.h=J8.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;g.Da(m)&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);g.Da(k)&&(l.currentIndex=k);c&&(this.Ra.listId=c);this.Ra.videoId=d;this.Ra.index=k||0;this.Ra.state=3;x8(this.Ra,m);this.o="UNSUPPORTED";K8("Connecting with setPlaylist and params: "+g.Gg(l));this.g.connect({method:"setPlaylist",
params:g.Gg(l)},a,Dqa())}else K8("Connecting without params"),this.g.connect({},a,Dqa());hsa(this)};
g.h.dispose=function(){this.ga()||(this.O("beforeDispose"),L8(this,3));g.O.prototype.dispose.call(this)};
g.h.W=function(){M8(this);O8(this);N8(this);g.kq(this.D);this.D=NaN;g.kq(this.F);this.F=NaN;this.l=null;g.qs(this.T);this.T.length=0;this.g.dispose();g.O.prototype.W.call(this);this.o=this.B=this.i=this.Ra=this.g=null};
g.h.UD=function(){this.Th(2)};
g.h.eJ=function(){K8("Channel opened");this.J&&(this.J=!1,N8(this),this.I=g.iq((0,g.y)(function(){K8("Timing out waiting for a screen.");this.Th(1)},this),15E3));
Hqa(rra(this.g),this.N)};
g.h.bJ=function(){K8("Channel closed");isNaN(this.A)?c7(!0):c7();this.dispose()};
g.h.cJ=function(a){c7();isNaN(this.Lj())?(K8("Channel error: "+a+" without reconnection"),this.dispose()):(this.J=!0,K8("Channel error: "+a+" with reconnection in "+this.Lj()+" ms"),L8(this,2))};
g.h.dJ=function(a){a.params?K8("Received: action="+a.action+", params="+g.Gg(a.params)):K8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=L6(a.params.devices);this.i=(0,g.ge)(a,function(c){return new O6(c)});
a=!!g.Wa(this.i,function(c){return"LOUNGE_SCREEN"==c.type});
ksa(this,a);break;case "loungeScreenDisconnected":g.db(this.i,function(c){return"LOUNGE_SCREEN"==c.type});
ksa(this,!1);break;case "remoteConnected":var b=new O6(L6(a.params.device));g.Wa(this.i,function(c){return b?c.id==b.id:!1})||sqa(this.i,b);
break;case "remoteDisconnected":b=new O6(L6(a.params.device));g.db(this.i,function(c){return b?c.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":msa(this,a);break;case "nowPlaying":osa(this,a);break;case "onStateChange":nsa(this,a);break;case "onAdStateChange":psa(this,a);break;case "onVolumeChanged":qsa(this,a);break;case "onSubtitlesTrackChanged":lsa(this,a);break;case "nowAutoplaying":rsa(this,a);break;case "autoplayDismissed":this.O("autoplayDismissed");break;case "autoplayUpNext":this.B=a.params.videoId||null;this.O("autoplayUpNext",this.B);break;case "onAutoplayModeChanged":this.o=
a.params.autoplayMode;this.O("autoplayModeChange",this.o);"DISABLED"==this.o&&this.O("autoplayDismissed");break;case "onHasPreviousNextChanged":ssa(this,a);break;case "requestAssistedSignIn":this.O("assistedSignInRequested",a.params.authCode);break;default:K8("Unrecognized action: "+a.action)}};
g.h.VM=function(){if(this.l){var a=this.l;this.l=null;this.Ra.videoId!=a&&P8(this,"getNowPlaying")}};
g.h.KD=function(){var a=3;this.ga()||(a=0,isNaN(this.Lj())?H7(this.g)&&isNaN(this.A)&&(a=1):a=2);return a};
g.h.Th=function(a){K8("Disconnecting with "+a);M8(this);this.O("beforeDisconnect",a);1==a&&c7();sra(this.g,a);this.dispose()};
g.h.JD=function(){var a=this.Ra;this.l&&(a=this.Ra.clone(),z8(a,this.l,a.index));return A8(a)};
g.h.jN=function(a){var b=new u8(a);b.videoId&&b.videoId!=this.Ra.videoId&&(this.l=b.videoId,g.kq(this.D),this.D=g.iq((0,g.y)(this.VM,this),5E3));var c=[];this.Ra.listId==b.listId&&this.Ra.videoId==b.videoId&&this.Ra.index==b.index||c.push("remoteQueueChange");this.Ra.playerState==b.playerState&&this.Ra.volume==b.volume&&this.Ra.muted==b.muted&&y8(this.Ra)==y8(b)&&g.Gg(this.Ra.g)==g.Gg(b.g)||c.push("remotePlayerChange");this.Ra.reset(a);(0,g.B)(c,function(d){this.O(d)},this)};
g.h.Hw=function(){var a=this.g.B.id,b=g.Wa(this.i,function(c){return"REMOTE_CONTROL"==c.type&&c.id!=a});
return b?b.id:""};
g.h.Lj=function(){var a=this.g;return a.i.isActive()?a.i.i-(0,g.H)():NaN};
g.h.CD=function(){return this.o||"UNSUPPORTED"};
g.h.DD=function(){return this.B||""};
g.h.TN=function(){if(!isNaN(this.Lj())){var a=this.g.i;g.Bo(a.g);a.start()}};
g.h.cN=function(a,b){P8(this,a,b);jsa(this)};
J8.prototype.subscribe=J8.prototype.subscribe;J8.prototype.unsubscribeByKey=J8.prototype.Mf;J8.prototype.getProxyState=J8.prototype.KD;J8.prototype.disconnect=J8.prototype.Th;J8.prototype.getPlayerContextData=J8.prototype.JD;J8.prototype.setPlayerContextData=J8.prototype.jN;J8.prototype.getOtherConnectedRemoteId=J8.prototype.Hw;J8.prototype.getReconnectTimeout=J8.prototype.Lj;J8.prototype.getAutoplayMode=J8.prototype.CD;J8.prototype.getAutoplayVideoId=J8.prototype.DD;J8.prototype.reconnect=J8.prototype.TN;
J8.prototype.sendMessage=J8.prototype.cN;g.t(Q8,Q7);g.h=Q8.prototype;g.h.Td=function(a){return this.bd.$_gs(a)};
g.h.contains=function(a){return!!this.bd.$_c(a)};
g.h.get=function(a){return this.bd.$_g(a)};
g.h.start=function(){this.bd.$_st()};
g.h.add=function(a,b,c){this.bd.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.bd.$_r(a,b,c)};
g.h.Lo=function(a,b,c,d){this.bd.$_un(a,b,c,d)};
g.h.W=function(){for(var a=0,b=this.i.length;a<b;++a)this.bd.$_ubk(this.i[a]);this.i.length=0;this.bd=null;Q7.prototype.W.call(this)};
g.h.XN=function(){this.O("screenChange")};
g.h.EK=function(){this.O("onlineScreenChange")};
Z7.prototype.$_st=Z7.prototype.start;Z7.prototype.$_gspc=Z7.prototype.YN;Z7.prototype.$_gsppc=Z7.prototype.VB;Z7.prototype.$_c=Z7.prototype.contains;Z7.prototype.$_g=Z7.prototype.get;Z7.prototype.$_a=Z7.prototype.add;Z7.prototype.$_un=Z7.prototype.Lo;Z7.prototype.$_r=Z7.prototype.remove;Z7.prototype.$_gs=Z7.prototype.Td;Z7.prototype.$_gos=Z7.prototype.UB;Z7.prototype.$_s=Z7.prototype.subscribe;Z7.prototype.$_ubk=Z7.prototype.Mf;var i9=null,h9=!1,R8=null,S8=null,g9=null,W8=[];g.t(j9,g.D);g.h=j9.prototype;
g.h.W=function(){g.D.prototype.W.call(this);this.o.stop();this.B.stop();this.J.stop();this.N();this.g.unsubscribe("proxyStateChange",this.Mz,this);this.g.unsubscribe("remotePlayerChange",this.Jk,this);this.g.unsubscribe("remoteQueueChange",this.ao,this);this.g.unsubscribe("autoplayUpNext",this.oz,this);this.g.unsubscribe("previousNextChange",this.Jz,this);this.g.unsubscribe("nowAutoplaying",this.Fz,this);this.g.unsubscribe("autoplayDismissed",this.nz,this);this.g=this.A=null};
g.h.ny=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.g.g)if(m9(this)){if(!D8(this.g).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":1==D8(this.g).playerState?this.g.pause():this.g.play();break;case "control_play":this.g.play();break;case "control_pause":this.g.pause();break;case "control_seek":this.I.Sj(c[0],c[1]);break;case "control_subtitles_set_track":n9(this,c[0]);break;case "control_set_audio_track":c=c[0],m9(this)&&this.g.setAudioTrack(this.i.getVideoData(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.i.getCurrentTime();o9(this,0==c?void 0:c);break;case "control_seek":o9(this,c[0]);break;case "control_subtitles_set_track":n9(this,c[0]);break;case "control_set_audio_track":c=c[0],m9(this)&&this.g.setAudioTrack(this.i.getVideoData(1).videoId,c)}};
g.h.YI=function(a){this.J.QD(a)};
g.h.CN=function(a){this.ny("control_subtitles_set_track",g.Yb(a)?null:a)};
g.h.hB=function(){var a=this.i.getOption("captions","track");g.Yb(a)||n9(this,a)};
g.h.Az=function(a){if(m9(this)){this.g.unsubscribe("remotePlayerChange",this.Jk,this);var b=Math.round(a.volume);a=!!a.muted;var c=D8(this.g);if(b!=c.volume||a!=c.muted)this.g.setVolume(b,a),this.T.start();this.g.subscribe("remotePlayerChange",this.Jk,this)}};
g.h.ZJ=function(){g.Yb(this.D)||Esa(this,this.D);this.F=!1};
g.h.Mz=function(a,b){this.B.stop();2==b&&this.gB()};
g.h.Jk=function(){if(m9(this)){this.o.stop();var a=D8(this.g);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.A.Zm=1;break;case 1082:case 1083:this.A.Zm=0;break;default:this.A.Zm=-1}switch(a.playerState){case 1081:case 1:l9(this,new g.ZC(8));this.fB();break;case 1085:case 3:l9(this,new g.ZC(9));break;case 1083:case 0:l9(this,new g.ZC(2));this.I.stop();k9(this,this.i.getVideoData().lengthSeconds);break;case 1084:l9(this,new g.ZC(4));break;case 2:l9(this,new g.ZC(4));k9(this,y8(a));
break;case -1:l9(this,new g.ZC(64));break;case -1E3:l9(this,new g.ZC(128,{errorCode:"mdx.remoteerror",errorMessage:"\uc774 \ub3d9\uc601\uc0c1\uc740 \uc6d0\uaca9\uc73c\ub85c \uc7ac\uc0dd\ud560 \uc218 \uc5c6\uc2b5\ub2c8\ub2e4."}))}a=D8(this.g).g;var b=this.D;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.kind==b.kind:1)||(this.D=a,Esa(this,a));a=D8(this.g);-1==a.volume||Math.round(this.i.getVolume())==a.volume&&this.i.isMuted()==a.muted||this.T.isActive()||
this.IB()}else Dsa(this)};
g.h.Jz=function(){this.i.O("mdxpreviousnextchange")};
g.h.ao=function(){m9(this)||Dsa(this)};
g.h.YC=function(){this.g.Sv()};
g.h.oz=function(a){a&&(a=g.fr("/watch_queue_ajax",{method:"GET",wd:{action_get_watch_queue_item:1,video_id:a},onSuccess:(0,g.y)(this.fM,this)}))&&(this.N=(0,g.y)(a.abort,a))};
g.h.fM=function(a,b){var c=new g.IB(g.X(this.i),{videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.i.O("mdxautoplayupnext",c)};
g.h.Fz=function(a){isNaN(a)||this.i.O("mdxnowautoplaying",a)};
g.h.nz=function(){this.i.O("mdxautoplaycanceled")};
g.h.uG=function(a,b){-1==D8(this.g).playerState?o9(this,a):b&&this.g.seekTo(a)};
g.h.IB=function(){if(m9(this)){var a=D8(this.g);this.l.Oa(this.R);a.muted?this.i.mute():this.i.unMute();this.i.setVolume(a.volume);this.R=this.l.L(this.i,"onVolumeChange",this.Az)}};
g.h.fB=function(){this.o.stop();if(!this.g.ga()){var a=D8(this.g);1==a.playerState&&l9(this,new g.ZC(8));k9(this,y8(a));this.o.start()}};
g.h.gB=function(){this.B.stop();this.o.stop();var a=this.g.o.getReconnectTimeout();2==this.g.g&&!isNaN(a)&&this.B.start()};g.t(p9,g.W);p9.prototype.o=function(){N6("mdx-privacy-popup-cancel");this.l.hide()};
p9.prototype.B=function(){N6("mdx-privacy-popup-confirm");this.l.hide()};g.t(q9,g.W);q9.prototype.A=function(a){Gsa(this,a.state)};g.t(r9,g.JU);r9.prototype.J=function(){var a=this.l.getOption("remote","receivers");a&&1<a.length&&!this.l.getOption("remote","quickCast")?(this.D=g.tb(a,this.B,this),g.LU(this,(0,g.ge)(a,this.B)),a=this.l.getOption("remote","currentReceiver"),this.pe(this.B(a)),this.enable(!0)):this.enable(!1)};
r9.prototype.B=function(a){return a.key};
r9.prototype.Be=function(a){return"cast-selector-receiver"==a?"\uc804\uc1a1...":this.D[a].name};
r9.prototype.Nc=function(a){g.JU.prototype.Nc.call(this,a);this.l.setOption("remote","currentReceiver",this.D[a]);this.o.ob()};g.t(s9,g.EL);g.h=s9.prototype;
g.h.create=function(){xsa(g.pz(g.X(this.player)));this.o.push(g.pq("yt-remote-before-disconnect",this.VI,this));this.o.push(g.pq("yt-remote-connection-change",this.hL,this));this.o.push(g.pq("yt-remote-receiver-availability-change",this.Kz,this));this.o.push(g.pq("yt-remote-auto-connect",this.fL,this));this.o.push(g.pq("yt-remote-receiver-resumed",this.eL,this));this.o.push(g.pq("mdx-privacy-popup-confirm",this.KM,this));this.o.push(g.pq("mdx-privacy-popup-cancel",this.JM,this));this.Kz()};
g.h.load=function(){this.player.cancelPlayback();g.EL.prototype.load.call(this);this.A=new j9(this,this.player,this.g);var a=(a=Csa())?a.currentTime:0;var b=f9()?new C8(a9(),void 0):null;0==a&&b&&(a=y8(D8(b)));0!=a&&this.Pc(a);Fsa(this,this.tk,this.tk);g.MY(this.player.app,6)};
g.h.unload=function(){this.player.O("mdxautoplaycanceled");this.l=this.i;g.nf(this.A,this.g);this.g=this.A=null;g.EL.prototype.unload.call(this);g.MY(this.player.app,5);t9(this)};
g.h.W=function(){g.qq(this.o);g.EL.prototype.W.call(this)};
g.h.df=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.A.ny.apply(this.A,[a].concat(g.ea(c)))};
g.h.getAdState=function(){return this.Zm};
g.h.MD=function(){return this.loaded?this.A.suggestion:null};
g.h.Pe=function(){return this.g?D8(this.g).Pe:!1};
g.h.hasNext=function(){return this.g?D8(this.g).hasNext:!1};
g.h.Pc=function(a,b){this.J=a||0;this.player.O("progresssync",a,b)};
g.h.getCurrentTime=function(){return this.J};
g.h.getProgressState=function(){var a=D8(this.g),b=this.player.getVideoData();return{allowSeeking:g.P(g.X(this.player).experiments,"web_player_mdx_allow_seeking_change_killswitch")?this.player.gc():!a.isAdPlaying()&&this.player.gc(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.A?a.l+w8(a):a.l,isAtLiveHead:1>=(a.A?a.i+w8(a):a.i)-this.getCurrentTime(),loaded:a.G,seekableEnd:a.A?a.i+w8(a):a.i,seekableStart:0<a.o?a.o+
w8(a):a.o}};
g.h.nextVideo=function(){this.g&&this.g.nextVideo()};
g.h.fo=function(){this.g&&this.g.fo()};
g.h.VI=function(a){1==a&&(this.I=this.g?D8(this.g):null)};
g.h.hL=function(){var a=f9()?new C8(a9(),void 0):null;if(a){var b=this.l;this.loaded&&this.unload();this.g=a;this.I=null;b.key!=this.i.key&&(this.l=b,this.load())}else g.mf(this.g),this.g=null,this.loaded&&(this.unload(),(a=this.I)&&a.videoId==this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,y8(a)));this.player.O("videodatachange","newdata",this.player.getVideoData(),3)};
g.h.Kz=function(){this.F=[this.i].concat(zsa());var a=b9()||this.i;u9(this,a);this.player.na("onMdxReceiversChange")};
g.h.DM=function(a){!this.G&&g.lE(a,8)&&(this.player.pauseVideo(),t9(this))};
g.h.fL=function(){var a=b9();u9(this,a)};
g.h.eL=function(){this.l=b9()};
g.h.KM=function(){this.G=!0;t9(this);h9=!1;i9&&d9(i9,1);i9=null};
g.h.JM=function(){this.G=!1;t9(this);u9(this,this.i);this.l=this.i;h9=!1;i9=null;this.player.playVideo()};
g.h.zc=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.F;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?s8():u9(this,b)),this.loaded?this.l:this.i;case "quickCast":return 2==this.F.length&&"cast-selector-receiver"==this.F[1].key?(b&&s8(),!0):!1}};
g.h.Ht=function(){this.g.Ht()};
g.h.Eb=function(){return!1};
g.h.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.aW.remote=s9;})(_yt_player);
